import type {
  PropertyListing,
  Lead,
  PriceTrend,
  LocalityInsight,
} from '@/types';

const IMAGES = [
  'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600&h=400&fit=crop',
  'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&h=400&fit=crop',
  'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=600&h=400&fit=crop',
  'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=600&h=400&fit=crop',
  'https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&h=400&fit=crop',
  'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600&h=400&fit=crop',
];

function img(index: number): string {
  return IMAGES[index % IMAGES.length];
}

export const mockListings: PropertyListing[] = [
  // ─── BUY APARTMENTS (8) ───────────────────────────────────────────
  {
    id: 'list-001',
    title: 'Spacious 2 BHK Apartment in Anna Nagar',
    description:
      'Well-ventilated 2 BHK apartment in a prime Anna Nagar location. Close to schools, hospitals, and shopping malls. Gated community with 24/7 security, power backup, and dedicated parking.',
    category: 'buy',
    propertyType: 'apartment',
    price: 6500000,
    priceLabel: '₹65 Lakhs',
    bhk: 2,
    bathrooms: 2,
    balconies: 1,
    floor: '5th of 12',
    totalFloors: 12,
    carpetArea: 980,
    furnishing: 'semifurnished',
    ageOfProperty: '3 years',
    possessionStatus: 'ready',
    locality: 'Anna Nagar',
    city: 'Chennai',
    state: 'Tamil Nadu',
    address: 'No 42, 3rd Avenue, Anna Nagar, Chennai - 600040',
    lat: 13.0872,
    lng: 80.2087,
    images: [img(0), img(1), img(2)],
    amenities: ['parking', 'security', 'lift', 'power-backup', 'garden', 'cctv'],
    verified: true,
    reraRegistered: true,
    reraId: 'TN/RERA/1234/2023',
    directFromOwner: false,
    ownerId: 'owner-001',
    ownerName: 'Rajesh Kumar',
    ownerPhone: '+91 98765 43210',
    views: 1243,
    createdAt: '2024-11-15T10:30:00.000Z',
    updatedAt: '2024-12-20T08:15:00.000Z',
  },
  {
    id: 'list-002',
    title: 'Luxury 3 BHK Flat at OMR with Sea View',
    description:
      'Premium 3 BHK apartment on Old Mahabalipuram Road with partial sea view. World-class amenities including swimming pool, gym, clubhouse. Proximity to IT parks and SIPCOT.',
    category: 'buy',
    propertyType: 'apartment',
    price: 12500000,
    priceLabel: '₹1.25 Cr',
    bhk: 3,
    bathrooms: 3,
    balconies: 2,
    floor: '14th of 22',
    totalFloors: 22,
    carpetArea: 1650,
    furnishing: 'furnished',
    ageOfProperty: 'New Launch',
    possessionStatus: 'ready',
    locality: 'OMR',
    city: 'Chennai',
    state: 'Tamil Nadu',
    address: 'Prestige Lakeside Habitat, OMR, Sholinganallur, Chennai - 600119',
    lat: 12.9010,
    lng: 80.2279,
    images: [img(1), img(2), img(3)],
    amenities: ['parking', 'gym', 'pool', 'security', 'lift', 'power-backup', 'clubhouse', 'jogging-track', 'children-play', 'cctv', 'intercom', 'vaastu'],
    verified: true,
    reraRegistered: true,
    reraId: 'TN/RERA/5678/2024',
    directFromOwner: false,
    ownerId: 'owner-002',
    ownerName: 'Prestige Constructions',
    ownerPhone: '+91 99876 54321',
    views: 2890,
    createdAt: '2024-10-05T09:00:00.000Z',
    updatedAt: '2024-12-18T14:30:00.000Z',
  },
  {
    id: 'list-003',
    title: 'Affordable 1 BHK near Velachery Metro',
    description:
      'Compact and well-designed 1 BHK apartment near Velachery Metro station. Ideal for first-time buyers. Walking distance to Phoenix Mall and Velachery market. Good rental potential.',
    category: 'buy',
    propertyType: 'apartment',
    price: 3500000,
    priceLabel: '₹35 Lakhs',
    bhk: 1,
    bathrooms: 1,
    balconies: 1,
    floor: '3rd of 7',
    totalFloors: 7,
    carpetArea: 550,
    furnishing: 'unfurnished',
    ageOfProperty: '5 years',
    possessionStatus: 'ready',
    locality: 'Velachery',
    city: 'Chennai',
    state: 'Tamil Nadu',
    address: 'Dwaraka Flats, 100 Feet Road, Velachery, Chennai - 600042',
    lat: 12.9816,
    lng: 80.2181,
    images: [img(2), img(3), img(4)],
    amenities: ['parking', 'lift', 'power-backup', 'water-supply', 'security'],
    verified: true,
    reraRegistered: false,
    directFromOwner: true,
    ownerId: 'owner-003',
    ownerName: 'Priya Sharma',
    ownerPhone: '+91 91234 56789',
    views: 876,
    createdAt: '2024-12-01T11:00:00.000Z',
    updatedAt: '2024-12-22T16:45:00.000Z',
  },
  {
    id: 'list-004',
    title: 'Premium 4 BHK in T Nagar – Heart of Chennai',
    description:
      'Ultra-premium 4 BHK apartment in the bustling T Nagar area. Fully furnished with Italian marble flooring. Walking distance to Panagal Park, Usman Road shopping. Perfect for luxury living.',
    category: 'buy',
    propertyType: 'apartment',
    price: 25000000,
    priceLabel: '₹2.5 Cr',
    bhk: 4,
    bathrooms: 4,
    balconies: 3,
    floor: '8th of 15',
    totalFloors: 15,
    carpetArea: 2400,
    superBuiltUpArea: 2800,
    furnishing: 'furnished',
    ageOfProperty: '1 year',
    possessionStatus: 'ready',
    locality: 'T Nagar',
    city: 'Chennai',
    state: 'Tamil Nadu',
    address: 'Ganga Tower, North Usman Road, T Nagar, Chennai - 600017',
    lat: 13.0418,
    lng: 80.2341,
    images: [img(3), img(4), img(5)],
    amenities: ['parking', 'gym', 'pool', 'security', 'lift', 'power-backup', 'clubhouse', 'cctv', 'intercom', 'ac', 'wifi', 'servant-room', 'vaastu'],
    verified: true,
    reraRegistered: true,
    reraId: 'TN/RERA/9012/2023',
    directFromOwner: false,
    ownerId: 'owner-004',
    ownerName: 'Vikram Real Estate',
    ownerPhone: '+91 98765 12345',
    views: 4521,
    createdAt: '2024-09-10T13:00:00.000Z',
    updatedAt: '2024-12-19T10:00:00.000Z',
  },
  {
    id: 'list-005',
    title: 'Modern 2 BHK at ECR – Beachside Living',
    description:
      'Contemporary 2 BHK apartment on East Coast Road with beach proximity. Open layout, large windows, and modern fittings. Gated community with landscaped gardens and jogging track.',
    category: 'buy',
    propertyType: 'apartment',
    price: 8500000,
    priceLabel: '₹85 Lakhs',
    bhk: 2,
    bathrooms: 2,
    balconies: 2,
    floor: '6th of 10',
    totalFloors: 10,
    carpetArea: 1150,
    furnishing: 'semifurnished',
    ageOfProperty: '2 years',
    possessionStatus: 'ready',
    locality: 'ECR',
    city: 'Chennai',
    state: 'Tamil Nadu',
    address: 'Casablanca Apartments, ECR, Neelangarai, Chennai - 600115',
    lat: 12.9516,
    lng: 80.2623,
    images: [img(4), img(5), img(0)],
    amenities: ['parking', 'gym', 'pool', 'security', 'garden', 'jogging-track', 'power-backup', 'cctv', 'vaastu'],
    verified: false,
    reraRegistered: true,
    reraId: 'TN/RERA/3456/2023',
    directFromOwner: true,
    ownerId: 'owner-005',
    ownerName: 'Anand Menon',
    ownerPhone: '+91 92345 67890',
    views: 1567,
    createdAt: '2024-10-20T07:30:00.000Z',
    updatedAt: '2024-12-15T12:00:00.000Z',
  },
  {
    id: 'list-006',
    title: 'Budget 1 BHK Apartment in Porur',
    description:
      'Compact 1 BHK apartment in Porur at an attractive price point. Near Porur Junction and DLF IT Park. Ideal for bachelors and small families. Well-maintained society with basic amenities.',
    category: 'buy',
    propertyType: 'apartment',
    price: 3200000,
    priceLabel: '₹32 Lakhs',
    bhk: 1,
    bathrooms: 1,
    balconies: 0,
    floor: '2nd of 5',
    totalFloors: 5,
    carpetArea: 480,
    furnishing: 'unfurnished',
    ageOfProperty: '7 years',
    possessionStatus: 'ready',
    locality: 'Porur',
    city: 'Chennai',
    state: 'Tamil Nadu',
    address: 'Krishna Residency, Mount-Poonamallee Road, Porur, Chennai - 600116',
    lat: 13.0387,
    lng: 80.1606,
    images: [img(5), img(0), img(1)],
    amenities: ['parking', 'water-supply', 'power-backup', 'security'],
    verified: false,
    reraRegistered: false,
    directFromOwner: true,
    ownerId: 'owner-006',
    ownerName: 'Lakshmi Iyer',
    ownerPhone: '+91 93456 78901',
    views: 543,
    createdAt: '2024-11-28T15:00:00.000Z',
    updatedAt: '2024-12-21T09:30:00.000Z',
  },
  {
    id: 'list-007',
    title: '3 BHK Flat in Adyar – Near Beach',
    description:
      'Spacious 3 BHK apartment in the serene Adyar locality. Close to Adyar beach, Theosophical Society, and top schools. Well-ventilated with cross ventilation. Ample natural light.',
    category: 'buy',
    propertyType: 'apartment',
    price: 14500000,
    priceLabel: '₹1.45 Cr',
    bhk: 3,
    bathrooms: 3,
    balconies: 2,
    floor: '7th of 14',
    totalFloors: 14,
    carpetArea: 1580,
    furnishing: 'semifurnished',
    ageOfProperty: '4 years',
    possessionStatus: 'ready',
    locality: 'Adyar',
    city: 'Chennai',
    state: 'Tamil Nadu',
    address: 'Adyar Gardens, Kasturba Nagar, Adyar, Chennai - 600020',
    lat: 13.0067,
    lng: 80.2572,
    images: [img(0), img(1), img(2)],
    amenities: ['parking', 'gym', 'security', 'lift', 'power-backup', 'garden', 'children-play', 'intercom', 'vaastu'],
    verified: true,
    reraRegistered: true,
    reraId: 'TN/RERA/7890/2023',
    directFromOwner: false,
    ownerId: 'owner-007',
    ownerName: 'Sundaram Properties',
    ownerPhone: '+91 94567 89012',
    views: 2134,
    createdAt: '2024-08-22T10:00:00.000Z',
    updatedAt: '2024-12-17T11:45:00.000Z',
  },
  {
    id: 'list-008',
    title: '3 BHK in Nungambakkam – Premium Location',
    description:
      'Elegant 3 BHK apartment in upscale Nungambakkam. Walking distance to Nungambakkam railway station and Sterling Road. Premium fittings, modular kitchen, and wooden flooring.',
    category: 'buy',
    propertyType: 'apartment',
    price: 18000000,
    priceLabel: '₹1.8 Cr',
    bhk: 3,
    bathrooms: 3,
    balconies: 2,
    floor: '10th of 18',
    totalFloors: 18,
    carpetArea: 1750,
    superBuiltUpArea: 2050,
    furnishing: 'furnished',
    ageOfProperty: '2 years',
    possessionStatus: 'ready',
    locality: 'Nungambakkam',
    city: 'Chennai',
    state: 'Tamil Nadu',
    address: 'Harrington Residences, Haddows Road, Nungambakkam, Chennai - 600034',
    lat: 13.0674,
    lng: 80.2376,
    images: [img(1), img(2), img(3)],
    amenities: ['parking', 'gym', 'pool', 'security', 'lift', 'power-backup', 'clubhouse', 'cctv', 'intercom', 'ac', 'vaastu', 'servant-room'],
    verified: true,
    reraRegistered: true,
    reraId: 'TN/RERA/2345/2024',
    directFromOwner: false,
    ownerId: 'owner-008',
    ownerName: 'Harrington Builders',
    ownerPhone: '+91 95678 90123',
    views: 3890,
    createdAt: '2024-09-25T08:30:00.000Z',
    updatedAt: '2024-12-22T07:00:00.000Z',
  },

  // ─── BUY VILLAS (2) ───────────────────────────────────────────────
  {
    id: 'list-009',
    title: 'Independent 4 BHK Villa in ECR',
    description:
      'Luxurious independent villa on ECR with private garden and terrace. Italian marble flooring, modular kitchen, and smart home features. 24/7 security with CCTV surveillance.',
    category: 'buy',
    propertyType: 'villa',
    price: 30000000,
    priceLabel: '₹3 Cr',
    bhk: 4,
    bathrooms: 4,
    balconies: 2,
    floor: 'Ground + 2',
    totalFloors: 3,
    carpetArea: 3200,
    superBuiltUpArea: 3800,
    plotArea: 2400,
    furnishing: 'furnished',
    ageOfProperty: '1 year',
    possessionStatus: 'ready',
    locality: 'ECR',
    city: 'Chennai',
    state: 'Tamil Nadu',
    address: 'Palm Grove Villas, ECR, Palavakkam, Chennai - 600100',
    lat: 12.9445,
    lng: 80.2569,
    images: [img(2), img(3), img(4)],
    amenities: ['parking', 'gym', 'pool', 'security', 'garden', 'power-backup', 'cctv', 'vaastu', 'servant-room', 'fire-safety'],
    verified: true,
    reraRegistered: true,
    reraId: 'TN/RERA/6789/2024',
    directFromOwner: true,
    ownerId: 'owner-009',
    ownerName: 'Deepak Reddy',
    ownerPhone: '+91 96789 01234',
    views: 5678,
    createdAt: '2024-07-15T12:00:00.000Z',
    updatedAt: '2024-12-20T18:00:00.000Z',
  },
  {
    id: 'list-010',
    title: '3 BHK Villa in Sholinganallur – Gated Community',
    description:
      'Beautiful 3 BHK villa in a well-planned gated community at Sholinganallur. Club house, swimming pool, and landscaped gardens. Close to OMR IT corridor. Ideal for families.',
    category: 'buy',
    propertyType: 'villa',
    price: 12500000,
    priceLabel: '₹1.25 Cr',
    bhk: 3,
    bathrooms: 3,
    balconies: 1,
    floor: 'Ground + 1',
    totalFloors: 2,
    carpetArea: 1800,
    plotArea: 1500,
    furnishing: 'semifurnished',
    ageOfProperty: '3 years',
    possessionStatus: 'ready',
    locality: 'Sholinganallur',
    city: 'Chennai',
    state: 'Tamil Nadu',
    address: 'Green Valley Villas, Rajiv Gandhi Salai, Sholinganallur, Chennai - 600119',
    lat: 12.9023,
    lng: 80.2256,
    images: [img(3), img(4), img(5)],
    amenities: ['parking', 'pool', 'security', 'garden', 'clubhouse', 'jogging-track', 'children-play', 'power-backup', 'cctv', 'vaastu'],
    verified: true,
    reraRegistered: true,
    reraId: 'TN/RERA/1357/2023',
    directFromOwner: false,
    ownerId: 'owner-010',
    ownerName: 'Green Valley Developers',
    ownerPhone: '+91 97890 12345',
    views: 2345,
    createdAt: '2024-10-10T09:00:00.000Z',
    updatedAt: '2024-12-18T13:00:00.000Z',
  },

  // ─── BUY PLOT (1) ─────────────────────────────────────────────────
  {
    id: 'list-011',
    title: 'Residential Plot in Kelambakkam – OMR Extension',
    description:
      'CMDA-approved residential plot on OMR extension near Kelambakkam. Excellent investment opportunity with rapid infrastructure development. Clear title, immediate registration possible.',
    category: 'buy',
    propertyType: 'plot',
    price: 4800000,
    priceLabel: '₹48 Lakhs',
    bhk: 0,
    bathrooms: 0,
    balconies: 0,
    floor: 'N/A',
    totalFloors: 0,
    carpetArea: 0,
    plotArea: 1200,
    furnishing: 'unfurnished',
    ageOfProperty: 'N/A',
    possessionStatus: 'ready',
    locality: 'Kelambakkam',
    city: 'Chennai',
    state: 'Tamil Nadu',
    address: 'GST Road Junction, Kelambakkam, Chennai - 603103',
    lat: 12.7906,
    lng: 80.2162,
    images: [img(4), img(5), img(0)],
    amenities: ['water-supply', 'power-backup'],
    verified: true,
    reraRegistered: false,
    directFromOwner: true,
    ownerId: 'owner-011',
    ownerName: 'Murugan Subramaniam',
    ownerPhone: '+91 98901 23456',
    views: 987,
    createdAt: '2024-11-05T14:00:00.000Z',
    updatedAt: '2024-12-16T10:30:00.000Z',
  },

  // ─── RENT APARTMENTS (4) ─────────────────────────────────────────
  {
    id: 'list-012',
    title: '1 BHK for Rent in Guindy – Near Metro',
    description:
      'Compact and well-maintained 1 BHK apartment available for immediate rent in Guindy. Close to Guindy metro station, railway station, and bus terminus. Ideal for IT professionals.',
    category: 'rent',
    propertyType: 'apartment',
    price: 12000,
    priceLabel: '₹12,000/month',
    deposit: 50000,
    bhk: 1,
    bathrooms: 1,
    balconies: 1,
    floor: '4th of 8',
    totalFloors: 8,
    carpetArea: 520,
    furnishing: 'semifurnished',
    ageOfProperty: '6 years',
    possessionStatus: 'ready',
    locality: 'Guindy',
    city: 'Chennai',
    state: 'Tamil Nadu',
    address: 'Sri Sai Residency, Mount-Poonamallee Road, Guindy, Chennai - 600032',
    lat: 13.0068,
    lng: 80.2206,
    images: [img(5), img(0), img(1)],
    amenities: ['parking', 'lift', 'power-backup', 'water-supply'],
    verified: true,
    reraRegistered: false,
    directFromOwner: true,
    ownerId: 'owner-012',
    ownerName: 'Senthil Kumar',
    ownerPhone: '+91 99012 34567',
    views: 765,
    createdAt: '2024-12-05T10:00:00.000Z',
    updatedAt: '2024-12-22T08:00:00.000Z',
  },
  {
    id: 'list-013',
    title: '2 BHK Flat for Rent in Anna Nagar',
    description:
      'Bright and airy 2 BHK flat in a well-maintained society in Anna Nagar. Near W Kilpauk Garden and Anna Nagar Tower. Covered car parking available. Family-friendly neighbourhood.',
    category: 'rent',
    propertyType: 'apartment',
    price: 22000,
    priceLabel: '₹22,000/month',
    deposit: 88000,
    bhk: 2,
    bathrooms: 2,
    balconies: 1,
    floor: '3rd of 6',
    totalFloors: 6,
    carpetArea: 900,
    furnishing: 'semifurnished',
    ageOfProperty: '4 years',
    possessionStatus: 'ready',
    locality: 'Anna Nagar',
    city: 'Chennai',
    state: 'Tamil Nadu',
    address: 'Thirumala Flats, 2nd Main Road, Anna Nagar, Chennai - 600040',
    lat: 13.0901,
    lng: 80.2123,
    images: [img(0), img(1), img(2)],
    amenities: ['parking', 'security', 'lift', 'power-backup', 'garden', 'children-play'],
    verified: true,
    reraRegistered: false,
    directFromOwner: false,
    ownerId: 'owner-013',
    ownerName: 'Nestaway Properties',
    ownerPhone: '+91 99123 45678',
    views: 1432,
    createdAt: '2024-11-20T08:00:00.000Z',
    updatedAt: '2024-12-21T14:00:00.000Z',
  },
  {
    id: 'list-014',
    title: '3 BHK for Rent in OMR – Furnished',
    description:
      'Fully furnished 3 BHK apartment for rent on OMR near Infosys campus. Comes with AC, washing machine, refrigerator, and modular kitchen. Perfect for IT families.',
    category: 'rent',
    propertyType: 'apartment',
    price: 45000,
    priceLabel: '₹45,000/month',
    deposit: 180000,
    bhk: 3,
    bathrooms: 3,
    balconies: 2,
    floor: '9th of 16',
    totalFloors: 16,
    carpetArea: 1600,
    furnishing: 'furnished',
    ageOfProperty: '2 years',
    possessionStatus: 'ready',
    locality: 'OMR',
    city: 'Chennai',
    state: 'Tamil Nadu',
    address: 'TVH Aura, Rajiv Gandhi Salai, Thoraipakkam, Chennai - 600097',
    lat: 12.9325,
    lng: 80.2314,
    images: [img(1), img(2), img(3)],
    amenities: ['parking', 'gym', 'pool', 'security', 'lift', 'power-backup', 'clubhouse', 'cctv', 'intercom', 'ac', 'wifi'],
    verified: true,
    reraRegistered: false,
    directFromOwner: false,
    ownerId: 'owner-014',
    ownerName: 'Property Manager Chennai',
    ownerPhone: '+91 99234 56789',
    views: 2100,
    createdAt: '2024-10-30T12:00:00.000Z',
    updatedAt: '2024-12-19T16:00:00.000Z',
  },
  {
    id: 'list-015',
    title: '1 BHK Semi-Furnished in Velachery – Budget Rent',
    description:
      'Affordable 1 BHK semi-furnished apartment in Velachery. Walking distance to Velachery Metro and bus stand. Good for bachelors and working professionals.',
    category: 'rent',
    propertyType: 'apartment',
    price: 15000,
    priceLabel: '₹15,000/month',
    deposit: 60000,
    bhk: 1,
    bathrooms: 1,
    balconies: 1,
    floor: '2nd of 4',
    totalFloors: 4,
    carpetArea: 500,
    furnishing: 'semifurnished',
    ageOfProperty: '8 years',
    possessionStatus: 'ready',
    locality: 'Velachery',
    city: 'Chennai',
    state: 'Tamil Nadu',
    address: 'Lakshmi Towers, Velachery Main Road, Chennai - 600042',
    lat: 12.9785,
    lng: 80.2204,
    images: [img(2), img(3), img(4)],
    amenities: ['parking', 'power-backup', 'water-supply'],
    verified: false,
    reraRegistered: false,
    directFromOwner: true,
    ownerId: 'owner-015',
    ownerName: 'Karthik Rajan',
    ownerPhone: '+91 99345 67890',
    views: 623,
    createdAt: '2024-12-10T11:00:00.000Z',
    updatedAt: '2024-12-20T09:00:00.000Z',
  },

  // ─── PG LISTING (1) ───────────────────────────────────────────────
  {
    id: 'list-016',
    title: 'Gents PG near OMR IT Corridor – Meals Included',
    description:
      'Premium gents PG accommodation near OMR IT corridor. Includes 3 meals a day, Wi-Fi, washing machine, daily housekeeping, and 24/7 security. AC and non-AC rooms available.',
    category: 'rent',
    propertyType: 'pg',
    price: 8000,
    priceLabel: '₹8,000/month',
    deposit: 16000,
    bhk: 1,
    bathrooms: 2,
    balconies: 0,
    floor: '1st of 3',
    totalFloors: 3,
    carpetArea: 200,
    furnishing: 'furnished',
    ageOfProperty: '2 years',
    possessionStatus: 'ready',
    locality: 'OMR',
    city: 'Chennai',
    state: 'Tamil Nadu',
    address: 'SRM Nagar, Semmancheri, OMR, Chennai - 600096',
    lat: 12.9155,
    lng: 80.2248,
    images: [img(3), img(4), img(5)],
    amenities: ['wifi', 'ac', 'power-backup', 'water-supply', 'security', 'cctv'],
    verified: true,
    reraRegistered: false,
    directFromOwner: true,
    ownerId: 'owner-016',
    ownerName: 'Stanford Living PG',
    ownerPhone: '+91 99456 78901',
    views: 1890,
    createdAt: '2024-11-10T09:00:00.000Z',
    updatedAt: '2024-12-22T06:00:00.000Z',
  },

  // ─── COMMERCIAL (2) ───────────────────────────────────────────────
  {
    id: 'list-017',
    title: 'Commercial Office Space in Guindy – 2000 sqft',
    description:
      'Fully air-conditioned commercial office space in a prime Guindy business district. Ideal for IT companies, startups, and consulting firms. Comes with 8 workstations, conference room, and reception.',
    category: 'commercial',
    propertyType: 'commercial-office',
    price: 85000,
    priceLabel: '₹85,000/month',
    deposit: 340000,
    bhk: 0,
    bathrooms: 2,
    balconies: 0,
    floor: '5th of 10',
    totalFloors: 10,
    carpetArea: 2000,
    furnishing: 'furnished',
    ageOfProperty: '3 years',
    possessionStatus: 'ready',
    locality: 'Guindy',
    city: 'Chennai',
    state: 'Tamil Nadu',
    address: 'SIDCO Industrial Estate, Guindy, Chennai - 600032',
    lat: 13.0085,
    lng: 80.2154,
    images: [img(4), img(5), img(0)],
    amenities: ['ac', 'lift', 'power-backup', 'cctv', 'parking', 'fire-safety', 'intercom', 'wifi'],
    verified: true,
    reraRegistered: false,
    directFromOwner: false,
    ownerId: 'owner-017',
    ownerName: 'Commercial Spaces India',
    ownerPhone: '+91 99567 89012',
    views: 1345,
    createdAt: '2024-09-18T10:00:00.000Z',
    updatedAt: '2024-12-18T12:00:00.000Z',
  },
  {
    id: 'list-018',
    title: 'Retail Shop in T Nagar – High Footfall Area',
    description:
      'Prime retail shop space in the busiest commercial area of T Nagar. Located on the ground floor of a commercial complex. Excellent for retail stores, restaurants, or showrooms. High footfall guaranteed.',
    category: 'commercial',
    propertyType: 'commercial-shop',
    price: 120000,
    priceLabel: '₹1.2 Lakh/month',
    deposit: 480000,
    bhk: 0,
    bathrooms: 1,
    balconies: 0,
    floor: 'Ground',
    totalFloors: 4,
    carpetArea: 650,
    furnishing: 'unfurnished',
    ageOfProperty: '5 years',
    possessionStatus: 'ready',
    locality: 'T Nagar',
    city: 'Chennai',
    state: 'Tamil Nadu',
    address: 'Ranganathan Street, T Nagar, Chennai - 600017',
    lat: 13.0432,
    lng: 80.2318,
    images: [img(5), img(0), img(1)],
    amenities: ['power-backup', 'cctv', 'parking', 'water-supply'],
    verified: false,
    reraRegistered: false,
    directFromOwner: true,
    ownerId: 'owner-018',
    ownerName: 'Meenakshi Sundaram',
    ownerPhone: '+91 99678 90123',
    views: 2567,
    createdAt: '2024-10-02T11:00:00.000Z',
    updatedAt: '2024-12-21T15:00:00.000Z',
  },
];

// ─── MOCK LEADS ──────────────────────────────────────────────────────

export const mockLeads: Lead[] = [
  {
    id: 'lead-001',
    listingId: 'list-001',
    listingTitle: 'Spacious 2 BHK Apartment in Anna Nagar',
    buyerName: 'Arun Vijay',
    buyerPhone: '+91 98700 11223',
    buyerEmail: 'arun.vijay@email.com',
    message:
      'Hi, I am interested in this 2 BHK apartment. Is it available for immediate site visit? Also, please share the maintenance charges and car parking details.',
    status: 'hot',
    createdAt: '2024-12-18T09:30:00.000Z',
  },
  {
    id: 'lead-002',
    listingId: 'list-002',
    listingTitle: 'Luxury 3 BHK Flat at OMR with Sea View',
    buyerName: 'Divya Krishnan',
    buyerPhone: '+91 98700 44556',
    buyerEmail: 'divya.k@email.com',
    message:
      'Looking for a 3 BHK near OMR IT corridor. Would like to schedule a visit this weekend. What is the EMI option available?',
    status: 'hot',
    createdAt: '2024-12-19T14:15:00.000Z',
  },
  {
    id: 'lead-003',
    listingId: 'list-013',
    listingTitle: '2 BHK Flat for Rent in Anna Nagar',
    buyerName: 'Rohit Mehta',
    buyerPhone: '+91 98700 77889',
    message:
      'Need a 2 BHK on rent in Anna Nagar for a family of 3. Is this pet-friendly? What is the lease duration and lock-in period?',
    status: 'warm',
    createdAt: '2024-12-20T11:00:00.000Z',
  },
  {
    id: 'lead-004',
    listingId: 'list-009',
    listingTitle: 'Independent 4 BHK Villa in ECR',
    buyerName: 'Sanjay Patel',
    buyerPhone: '+91 98700 99001',
    buyerEmail: 'sanjay.patel@email.com',
    message:
      'I am a NRI interested in this villa for investment. Can you provide a video tour? Also, what is the resale potential in this area?',
    status: 'warm',
    createdAt: '2024-12-21T16:45:00.000Z',
  },
  {
    id: 'lead-005',
    listingId: 'list-017',
    listingTitle: 'Commercial Office Space in Guindy – 2000 sqft',
    buyerName: 'Priya Chandrasekaran',
    buyerPhone: '+91 98700 22334',
    buyerEmail: 'priya.cs@startup.com',
    message:
      'We are a 15-member startup looking for office space. Is there scope for expansion? What are the terms for a 3-year lease?',
    status: 'cold',
    createdAt: '2024-12-22T08:30:00.000Z',
  },
];

// ─── MOCK PRICE TRENDS ───────────────────────────────────────────────

export const mockPriceTrends: Record<string, PriceTrend[]> = {
  'Anna Nagar': [
    { month: 'Jan', price: 6200 },
    { month: 'Feb', price: 6250 },
    { month: 'Mar', price: 6300 },
    { month: 'Apr', price: 6280 },
    { month: 'May', price: 6400 },
    { month: 'Jun', price: 6500 },
    { month: 'Jul', price: 6550 },
    { month: 'Aug', price: 6700 },
    { month: 'Sep', price: 6850 },
    { month: 'Oct', price: 7000 },
    { month: 'Nov', price: 7150 },
    { month: 'Dec', price: 7350 },
  ],
  OMR: [
    { month: 'Jan', price: 5500 },
    { month: 'Feb', price: 5520 },
    { month: 'Mar', price: 5580 },
    { month: 'Apr', price: 5600 },
    { month: 'May', price: 5650 },
    { month: 'Jun', price: 5700 },
    { month: 'Jul', price: 5720 },
    { month: 'Aug', price: 5780 },
    { month: 'Sep', price: 5850 },
    { month: 'Oct', price: 5900 },
    { month: 'Nov', price: 6000 },
    { month: 'Dec', price: 6100 },
  ],
  Velachery: [
    { month: 'Jan', price: 5800 },
    { month: 'Feb', price: 5850 },
    { month: 'Mar', price: 5820 },
    { month: 'Apr', price: 5900 },
    { month: 'May', price: 5950 },
    { month: 'Jun', price: 6000 },
    { month: 'Jul', price: 6050 },
    { month: 'Aug', price: 6100 },
    { month: 'Sep', price: 6150 },
    { month: 'Oct', price: 6200 },
    { month: 'Nov', price: 6300 },
    { month: 'Dec', price: 6400 },
  ],
};

// ─── MOCK LOCALITY INSIGHTS ─────────────────────────────────────────

export const mockLocalityInsights: Record<string, LocalityInsight> = {
  'Anna Nagar': {
    safety: 4.5,
    connectivity: 4.0,
    infrastructure: 4.5,
    airQuality: 3.5,
    nightlife: 3.5,
    restaurants: 4.0,
  },
  OMR: {
    safety: 4.0,
    connectivity: 3.5,
    infrastructure: 4.0,
    airQuality: 4.0,
    nightlife: 3.0,
    restaurants: 3.5,
  },
  Velachery: {
    safety: 4.0,
    connectivity: 4.5,
    infrastructure: 4.0,
    airQuality: 3.0,
    nightlife: 4.0,
    restaurants: 4.5,
  },
};
