import type {
  PropertyListing,
  Lead,
  PriceTrend,
  LocalityInsight,
} from '@/types';

const IMAGES = [
  'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600&h=400&fit=crop',
  'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&h=400&fit=crop',
  'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=600&h=400&fit=crop',
  'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=600&h=400&fit=crop',
  'https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&h=400&fit=crop',
  'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600&h=400&fit=crop',
];

function img(index: number): string {
  return IMAGES[index % IMAGES.length];
}

export const mockListings: PropertyListing[] = [
  // ─── BUY APARTMENTS (8) ───────────────────────────────────────────
  {
    id: 'list-001',
    title: 'Spacious 2 BHK Apartment in Anna Nagar',
    description:
      'Well-ventilated 2 BHK apartment in a prime Anna Nagar location. Close to schools, hospitals, and shopping malls. Gated community with 24/7 security, power backup, and dedicated parking.',
    category: 'buy',
    propertyType: 'apartment',
    price: 6500000,
    priceLabel: '₹65 Lakhs',
    bhk: 2,
    bathrooms: 2,
    balconies: 1,
    floor: '5th of 12',
    totalFloors: 12,
    carpetArea: 980,
    furnishing: 'semifurnished',
    ageOfProperty: '3 years',
    possessionStatus: 'ready',
    locality: 'Anna Nagar',
    city: 'Chennai',
    state: 'Tamil Nadu',
    address: 'No 42, 3rd Avenue, Anna Nagar, Chennai - 600040',
    lat: 13.0872,
    lng: 80.2087,
    images: [img(0), img(1), img(2)],
    amenities: ['parking', 'security', 'lift', 'power-backup', 'garden', 'cctv'],
    verified: true,
    reraRegistered: true,
    reraId: 'TN/RERA/1234/2023',
    directFromOwner: false,
    ownerId: 'owner-001',
    ownerName: 'Rajesh Kumar',
    ownerPhone: '+91 98765 43210',
    views: 1243,
    createdAt: '2024-11-15T10:30:00.000Z',
    updatedAt: '2024-12-20T08:15:00.000Z',
  },
  {
    id: 'list-002',
    title: 'Luxury 3 BHK Flat at OMR with Sea View',
    description:
      'Premium 3 BHK apartment on Old Mahabalipuram Road with partial sea view. World-class amenities including swimming pool, gym, clubhouse. Proximity to IT parks and SIPCOT.',
    category: 'buy',
    propertyType: 'apartment',
    price: 12500000,
    priceLabel: '₹1.25 Cr',
    bhk: 3,
    bathrooms: 3,
    balconies: 2,
    floor: '14th of 22',
    totalFloors: 22,
    carpetArea: 1650,
    furnishing: 'furnished',
    ageOfProperty: 'New Launch',
    possessionStatus: 'ready',
    locality: 'OMR',
    city: 'Chennai',
    state: 'Tamil Nadu',
    address: 'Prestige Lakeside Habitat, OMR, Sholinganallur, Chennai - 600119',
    lat: 12.9010,
    lng: 80.2279,
    images: [img(1), img(2), img(3)],
    amenities: ['parking', 'gym', 'pool', 'security', 'lift', 'power-backup', 'clubhouse', 'jogging-track', 'children-play', 'cctv', 'intercom', 'vaastu'],
    verified: true,
    reraRegistered: true,
    reraId: 'TN/RERA/5678/2024',
    directFromOwner: false,
    ownerId: 'owner-002',
    ownerName: 'Prestige Constructions',
    ownerPhone: '+91 99876 54321',
    views: 2890,
    createdAt: '2024-10-05T09:00:00.000Z',
    updatedAt: '2024-12-18T14:30:00.000Z',
  },
  {
    id: 'list-003',
    title: 'Affordable 1 BHK near Velachery Metro',
    description:
      'Compact and well-designed 1 BHK apartment near Velachery Metro station. Ideal for first-time buyers. Walking distance to Phoenix Mall and Velachery market. Good rental potential.',
    category: 'buy',
    propertyType: 'apartment',
    price: 3500000,
    priceLabel: '₹35 Lakhs',
    bhk: 1,
    bathrooms: 1,
    balconies: 1,
    floor: '3rd of 7',
    totalFloors: 7,
    carpetArea: 550,
    furnishing: 'unfurnished',
    ageOfProperty: '5 years',
    possessionStatus: 'ready',
    locality: 'Velachery',
    city: 'Chennai',
    state: 'Tamil Nadu',
    address: 'Dwaraka Flats, 100 Feet Road, Velachery, Chennai - 600042',
    lat: 12.9816,
    lng: 80.2181,
    images: [img(2), img(3), img(4)],
    amenities: ['parking', 'lift', 'power-backup', 'water-supply', 'security'],
    verified: true,
    reraRegistered: false,
    directFromOwner: true,
    ownerId: 'owner-003',
    ownerName: 'Priya Sharma',
    ownerPhone: '+91 91234 56789',
    views: 876,
    createdAt: '2024-12-01T11:00:00.000Z',
    updatedAt: '2024-12-22T16:45:00.000Z',
  },
  {
    id: 'list-004',
    title: 'Premium 4 BHK in T Nagar – Heart of Chennai',
    description:
      'Ultra-premium 4 BHK apartment in the bustling T Nagar area. Fully furnished with Italian marble flooring. Walking distance to Panagal Park, Usman Road shopping. Perfect for luxury living.',
    category: 'buy',
    propertyType: 'apartment',
    price: 25000000,
    priceLabel: '₹2.5 Cr',
    bhk: 4,
    bathrooms: 4,
    balconies: 3,
    floor: '8th of 15',
    totalFloors: 15,
    carpetArea: 2400,
    superBuiltUpArea: 2800,
    furnishing: 'furnished',
    ageOfProperty: '1 year',
    possessionStatus: 'ready',
    locality: 'T Nagar',
    city: 'Chennai',
    state: 'Tamil Nadu',
    address: 'Ganga Tower, North Usman Road, T Nagar, Chennai - 600017',
    lat: 13.0418,
    lng: 80.2341,
    images: [img(3), img(4), img(5)],
    amenities: ['parking', 'gym', 'pool', 'security', 'lift', 'power-backup', 'clubhouse', 'cctv', 'intercom', 'ac', 'wifi', 'servant-room', 'vaastu'],
    verified: true,
    reraRegistered: true,
    reraId: 'TN/RERA/9012/2023',
    directFromOwner: false,
    ownerId: 'owner-004',
    ownerName: 'Vikram Real Estate',
    ownerPhone: '+91 98765 12345',
    views: 4521,
    createdAt: '2024-09-10T13:00:00.000Z',
    updatedAt: '2024-12-19T10:00:00.000Z',
  },
  {
    id: 'list-005',
    title: 'Modern 2 BHK at ECR – Beachside Living',
    description:
      'Contemporary 2 BHK apartment on East Coast Road with beach proximity. Open layout, large windows, and modern fittings. Gated community with landscaped gardens and jogging track.',
    category: 'buy',
    propertyType: 'apartment',
    price: 8500000,
    priceLabel: '₹85 Lakhs',
    bhk: 2,
    bathrooms: 2,
    balconies: 2,
    floor: '6th of 10',
    totalFloors: 10,
    carpetArea: 1150,
    furnishing: 'semifurnished',
    ageOfProperty: '2 years',
    possessionStatus: 'ready',
    locality: 'ECR',
    city: 'Chennai',
    state: 'Tamil Nadu',
    address: 'Casablanca Apartments, ECR, Neelangarai, Chennai - 600115',
    lat: 12.9516,
    lng: 80.2623,
    images: [img(4), img(5), img(0)],
    amenities: ['parking', 'gym', 'pool', 'security', 'garden', 'jogging-track', 'power-backup', 'cctv', 'vaastu'],
    verified: false,
    reraRegistered: true,
    reraId: 'TN/RERA/3456/2023',
    directFromOwner: true,
    ownerId: 'owner-005',
    ownerName: 'Anand Menon',
    ownerPhone: '+91 92345 67890',
    views: 1567,
    createdAt: '2024-10-20T07:30:00.000Z',
    updatedAt: '2024-12-15T12:00:00.000Z',
  },
  {
    id: 'list-006',
    title: 'Budget 1 BHK Apartment in Porur',
    description:
      'Compact 1 BHK apartment in Porur at an attractive price point. Near Porur Junction and DLF IT Park. Ideal for bachelors and small families. Well-maintained society with basic amenities.',
    category: 'buy',
    propertyType: 'apartment',
    price: 3200000,
    priceLabel: '₹32 Lakhs',
    bhk: 1,
    bathrooms: 1,
    balconies: 0,
    floor: '2nd of 5',
    totalFloors: 5,
    carpetArea: 480,
    furnishing: 'unfurnished',
    ageOfProperty: '7 years',
    possessionStatus: 'ready',
    locality: 'Porur',
    city: 'Chennai',
    state: 'Tamil Nadu',
    address: 'Krishna Residency, Mount-Poonamallee Road, Porur, Chennai - 600116',
    lat: 13.0387,
    lng: 80.1606,
    images: [img(5), img(0), img(1)],
    amenities: ['parking', 'water-supply', 'power-backup', 'security'],
    verified: false,
    reraRegistered: false,
    directFromOwner: true,
    ownerId: 'owner-006',
    ownerName: 'Lakshmi Iyer',
    ownerPhone: '+91 93456 78901',
    views: 543,
    createdAt: '2024-11-28T15:00:00.000Z',
    updatedAt: '2024-12-21T09:30:00.000Z',
  },
  {
    id: 'list-007',
    title: '3 BHK Flat in Adyar – Near Beach',
    description:
      'Spacious 3 BHK apartment in the serene Adyar locality. Close to Adyar beach, Theosophical Society, and top schools. Well-ventilated with cross ventilation. Ample natural light.',
    category: 'buy',
    propertyType: 'apartment',
    price: 14500000,
    priceLabel: '₹1.45 Cr',
    bhk: 3,
    bathrooms: 3,
    balconies: 2,
    floor: '7th of 14',
    totalFloors: 14,
    carpetArea: 1580,
    furnishing: 'semifurnished',
    ageOfProperty: '4 years',
    possessionStatus: 'ready',
    locality: 'Adyar',
    city: 'Chennai',
    state: 'Tamil Nadu',
    address: 'Adyar Gardens, Kasturba Nagar, Adyar, Chennai - 600020',
    lat: 13.0067,
    lng: 80.2572,
    images: [img(0), img(1), img(2)],
    amenities: ['parking', 'gym', 'security', 'lift', 'power-backup', 'garden', 'children-play', 'intercom', 'vaastu'],
    verified: true,
    reraRegistered: true,
    reraId: 'TN/RERA/7890/2023',
    directFromOwner: false,
    ownerId: 'owner-007',
    ownerName: 'Sundaram Properties',
    ownerPhone: '+91 94567 89012',
    views: 2134,
    createdAt: '2024-08-22T10:00:00.000Z',
    updatedAt: '2024-12-17T11:45:00.000Z',
  },
  {
    id: 'list-008',
    title: '3 BHK in Nungambakkam – Premium Location',
    description:
      'Elegant 3 BHK apartment in upscale Nungambakkam. Walking distance to Nungambakkam railway station and Sterling Road. Premium fittings, modular kitchen, and wooden flooring.',
    category: 'buy',
    propertyType: 'apartment',
    price: 18000000,
    priceLabel: '₹1.8 Cr',
    bhk: 3,
    bathrooms: 3,
    balconies: 2,
    floor: '10th of 18',
    totalFloors: 18,
    carpetArea: 1750,
    superBuiltUpArea: 2050,
    furnishing: 'furnished',
    ageOfProperty: '2 years',
    possessionStatus: 'ready',
    locality: 'Nungambakkam',
    city: 'Chennai',
    state: 'Tamil Nadu',
    address: 'Harrington Residences, Haddows Road, Nungambakkam, Chennai - 600034',
    lat: 13.0674,
    lng: 80.2376,
    images: [img(1), img(2), img(3)],
    amenities: ['parking', 'gym', 'pool', 'security', 'lift', 'power-backup', 'clubhouse', 'cctv', 'intercom', 'ac', 'vaastu', 'servant-room'],
    verified: true,
    reraRegistered: true,
    reraId: 'TN/RERA/2345/2024',
    directFromOwner: false,
    ownerId: 'owner-008',
    ownerName: 'Harrington Builders',
    ownerPhone: '+91 95678 90123',
    views: 3890,
    createdAt: '2024-09-25T08:30:00.000Z',
    updatedAt: '2024-12-22T07:00:00.000Z',
  },

  // ─── BUY VILLAS (2) ───────────────────────────────────────────────
  {
    id: 'list-009',
    title: 'Independent 4 BHK Villa in ECR',
    description:
      'Luxurious independent villa on ECR with private garden and terrace. Italian marble flooring, modular kitchen, and smart home features. 24/7 security with CCTV surveillance.',
    category: 'buy',
    propertyType: 'villa',
    price: 30000000,
    priceLabel: '₹3 Cr',
    bhk: 4,
    bathrooms: 4,
    balconies: 2,
    floor: 'Ground + 2',
    totalFloors: 3,
    carpetArea: 3200,
    superBuiltUpArea: 3800,
    plotArea: 2400,
    furnishing: 'furnished',
    ageOfProperty: '1 year',
    possessionStatus: 'ready',
    locality: 'ECR',
    city: 'Chennai',
    state: 'Tamil Nadu',
    address: 'Palm Grove Villas, ECR, Palavakkam, Chennai - 600100',
    lat: 12.9445,
    lng: 80.2569,
    images: [img(2), img(3), img(4)],
    amenities: ['parking', 'gym', 'pool', 'security', 'garden', 'power-backup', 'cctv', 'vaastu', 'servant-room', 'fire-safety'],
    verified: true,
    reraRegistered: true,
    reraId: 'TN/RERA/6789/2024',
    directFromOwner: true,
    ownerId: 'owner-009',
    ownerName: 'Deepak Reddy',
    ownerPhone: '+91 96789 01234',
    views: 5678,
    createdAt: '2024-07-15T12:00:00.000Z',
    updatedAt: '2024-12-20T18:00:00.000Z',
  },
  {
    id: 'list-010',
    title: '3 BHK Villa in Sholinganallur – Gated Community',
    description:
      'Beautiful 3 BHK villa in a well-planned gated community at Sholinganallur. Club house, swimming pool, and landscaped gardens. Close to OMR IT corridor. Ideal for families.',
    category: 'buy',
    propertyType: 'villa',
    price: 12500000,
    priceLabel: '₹1.25 Cr',
    bhk: 3,
    bathrooms: 3,
    balconies: 1,
    floor: 'Ground + 1',
    totalFloors: 2,
    carpetArea: 1800,
    plotArea: 1500,
    furnishing: 'semifurnished',
    ageOfProperty: '3 years',
    possessionStatus: 'ready',
    locality: 'Sholinganallur',
    city: 'Chennai',
    state: 'Tamil Nadu',
    address: 'Green Valley Villas, Rajiv Gandhi Salai, Sholinganallur, Chennai - 600119',
    lat: 12.9023,
    lng: 80.2256,
    images: [img(3), img(4), img(5)],
    amenities: ['parking', 'pool', 'security', 'garden', 'clubhouse', 'jogging-track', 'children-play', 'power-backup', 'cctv', 'vaastu'],
    verified: true,
    reraRegistered: true,
    reraId: 'TN/RERA/1357/2023',
    directFromOwner: false,
    ownerId: 'owner-010',
    ownerName: 'Green Valley Developers',
    ownerPhone: '+91 97890 12345',
    views: 2345,
    createdAt: '2024-10-10T09:00:00.000Z',
    updatedAt: '2024-12-18T13:00:00.000Z',
  },

  // ─── BUY PLOT (1) ─────────────────────────────────────────────────
  {
    id: 'list-011',
    title: 'Residential Plot in Kelambakkam – OMR Extension',
    description:
      'CMDA-approved residential plot on OMR extension near Kelambakkam. Excellent investment opportunity with rapid infrastructure development. Clear title, immediate registration possible.',
    category: 'buy',
    propertyType: 'plot',
    price: 4800000,
    priceLabel: '₹48 Lakhs',
    bhk: 0,
    bathrooms: 0,
    balconies: 0,
    floor: 'N/A',
    totalFloors: 0,
    carpetArea: 0,
    plotArea: 1200,
    furnishing: 'unfurnished',
    ageOfProperty: 'N/A',
    possessionStatus: 'ready',
    locality: 'Kelambakkam',
    city: 'Chennai',
    state: 'Tamil Nadu',
    address: 'GST Road Junction, Kelambakkam, Chennai - 603103',
    lat: 12.7906,
    lng: 80.2162,
    images: [img(4), img(5), img(0)],
    amenities: ['water-supply', 'power-backup'],
    verified: true,
    reraRegistered: false,
    directFromOwner: true,
    ownerId: 'owner-011',
    ownerName: 'Murugan Subramaniam',
    ownerPhone: '+91 98901 23456',
    views: 987,
    createdAt: '2024-11-05T14:00:00.000Z',
    updatedAt: '2024-12-16T10:30:00.000Z',
  },

  // ─── RENT APARTMENTS (4) ─────────────────────────────────────────
  {
    id: 'list-012',
    title: '1 BHK for Rent in Guindy – Near Metro',
    description:
      'Compact and well-maintained 1 BHK apartment available for immediate rent in Guindy. Close to Guindy metro station, railway station, and bus terminus. Ideal for IT professionals.',
    category: 'rent',
    propertyType: 'apartment',
    price: 12000,
    priceLabel: '₹12,000/month',
    deposit: 50000,
    bhk: 1,
    bathrooms: 1,
    balconies: 1,
    floor: '4th of 8',
    totalFloors: 8,
    carpetArea: 520,
    furnishing: 'semifurnished',
    ageOfProperty: '6 years',
    possessionStatus: 'ready',
    locality: 'Guindy',
    city: 'Chennai',
    state: 'Tamil Nadu',
    address: 'Sri Sai Residency, Mount-Poonamallee Road, Guindy, Chennai - 600032',
    lat: 13.0068,
    lng: 80.2206,
    images: [img(5), img(0), img(1)],
    amenities: ['parking', 'lift', 'power-backup', 'water-supply'],
    verified: true,
    reraRegistered: false,
    directFromOwner: true,
    ownerId: 'owner-012',
    ownerName: 'Senthil Kumar',
    ownerPhone: '+91 99012 34567',
    views: 765,
    createdAt: '2024-12-05T10:00:00.000Z',
    updatedAt: '2024-12-22T08:00:00.000Z',
  },
  {
    id: 'list-013',
    title: '2 BHK Flat for Rent in Anna Nagar',
    description:
      'Bright and airy 2 BHK flat in a well-maintained society in Anna Nagar. Near W Kilpauk Garden and Anna Nagar Tower. Covered car parking available. Family-friendly neighbourhood.',
    category: 'rent',
    propertyType: 'apartment',
    price: 22000,
    priceLabel: '₹22,000/month',
    deposit: 88000,
    bhk: 2,
    bathrooms: 2,
    balconies: 1,
    floor: '3rd of 6',
    totalFloors: 6,
    carpetArea: 900,
    furnishing: 'semifurnished',
    ageOfProperty: '4 years',
    possessionStatus: 'ready',
    locality: 'Anna Nagar',
    city: 'Chennai',
    state: 'Tamil Nadu',
    address: 'Thirumala Flats, 2nd Main Road, Anna Nagar, Chennai - 600040',
    lat: 13.0901,
    lng: 80.2123,
    images: [img(0), img(1), img(2)],
    amenities: ['parking', 'security', 'lift', 'power-backup', 'garden', 'children-play'],
    verified: true,
    reraRegistered: false,
    directFromOwner: false,
    ownerId: 'owner-013',
    ownerName: 'Nestaway Properties',
    ownerPhone: '+91 99123 45678',
    views: 1432,
    createdAt: '2024-11-20T08:00:00.000Z',
    updatedAt: '2024-12-21T14:00:00.000Z',
  },
  {
    id: 'list-014',
    title: '3 BHK for Rent in OMR – Furnished',
    description:
      'Fully furnished 3 BHK apartment for rent on OMR near Infosys campus. Comes with AC, washing machine, refrigerator, and modular kitchen. Perfect for IT families.',
    category: 'rent',
    propertyType: 'apartment',
    price: 45000,
    priceLabel: '₹45,000/month',
    deposit: 180000,
    bhk: 3,
    bathrooms: 3,
    balconies: 2,
    floor: '9th of 16',
    totalFloors: 16,
    carpetArea: 1600,
    furnishing: 'furnished',
    ageOfProperty: '2 years',
    possessionStatus: 'ready',
    locality: 'OMR',
    city: 'Chennai',
    state: 'Tamil Nadu',
    address: 'TVH Aura, Rajiv Gandhi Salai, Thoraipakkam, Chennai - 600097',
    lat: 12.9325,
    lng: 80.2314,
    images: [img(1), img(2), img(3)],
    amenities: ['parking', 'gym', 'pool', 'security', 'lift', 'power-backup', 'clubhouse', 'cctv', 'intercom', 'ac', 'wifi'],
    verified: true,
    reraRegistered: false,
    directFromOwner: false,
    ownerId: 'owner-014',
    ownerName: 'Property Manager Chennai',
    ownerPhone: '+91 99234 56789',
    views: 2100,
    createdAt: '2024-10-30T12:00:00.000Z',
    updatedAt: '2024-12-19T16:00:00.000Z',
  },
  {
    id: 'list-015',
    title: '1 BHK Semi-Furnished in Velachery – Budget Rent',
    description:
      'Affordable 1 BHK semi-furnished apartment in Velachery. Walking distance to Velachery Metro and bus stand. Good for bachelors and working professionals.',
    category: 'rent',
    propertyType: 'apartment',
    price: 15000,
    priceLabel: '₹15,000/month',
    deposit: 60000,
    bhk: 1,
    bathrooms: 1,
    balconies: 1,
    floor: '2nd of 4',
    totalFloors: 4,
    carpetArea: 500,
    furnishing: 'semifurnished',
    ageOfProperty: '8 years',
    possessionStatus: 'ready',
    locality: 'Velachery',
    city: 'Chennai',
    state: 'Tamil Nadu',
    address: 'Lakshmi Towers, Velachery Main Road, Chennai - 600042',
    lat: 12.9785,
    lng: 80.2204,
    images: [img(2), img(3), img(4)],
    amenities: ['parking', 'power-backup', 'water-supply'],
    verified: false,
    reraRegistered: false,
    directFromOwner: true,
    ownerId: 'owner-015',
    ownerName: 'Karthik Rajan',
    ownerPhone: '+91 99345 67890',
    views: 623,
    createdAt: '2024-12-10T11:00:00.000Z',
    updatedAt: '2024-12-20T09:00:00.000Z',
  },

  // ─── PG LISTING (1) ───────────────────────────────────────────────
  {
    id: 'list-016',
    title: 'Gents PG near OMR IT Corridor – Meals Included',
    description:
      'Premium gents PG accommodation near OMR IT corridor. Includes 3 meals a day, Wi-Fi, washing machine, daily housekeeping, and 24/7 security. AC and non-AC rooms available.',
    category: 'rent',
    propertyType: 'pg',
    price: 8000,
    priceLabel: '₹8,000/month',
    deposit: 16000,
    bhk: 1,
    bathrooms: 2,
    balconies: 0,
    floor: '1st of 3',
    totalFloors: 3,
    carpetArea: 200,
    furnishing: 'furnished',
    ageOfProperty: '2 years',
    possessionStatus: 'ready',
    locality: 'OMR',
    city: 'Chennai',
    state: 'Tamil Nadu',
    address: 'SRM Nagar, Semmancheri, OMR, Chennai - 600096',
    lat: 12.9155,
    lng: 80.2248,
    images: [img(3), img(4), img(5)],
    amenities: ['wifi', 'ac', 'power-backup', 'water-supply', 'security', 'cctv'],
    verified: true,
    reraRegistered: false,
    directFromOwner: true,
    ownerId: 'owner-016',
    ownerName: 'Stanford Living PG',
    ownerPhone: '+91 99456 78901',
    views: 1890,
    createdAt: '2024-11-10T09:00:00.000Z',
    updatedAt: '2024-12-22T06:00:00.000Z',
  },

  // ─── COMMERCIAL (2) ───────────────────────────────────────────────
  {
    id: 'list-017',
    title: 'Commercial Office Space in Guindy – 2000 sqft',
    description:
      'Fully air-conditioned commercial office space in a prime Guindy business district. Ideal for IT companies, startups, and consulting firms. Comes with 8 workstations, conference room, and reception.',
    category: 'commercial',
    propertyType: 'commercial-office',
    price: 85000,
    priceLabel: '₹85,000/month',
    deposit: 340000,
    bhk: 0,
    bathrooms: 2,
    balconies: 0,
    floor: '5th of 10',
    totalFloors: 10,
    carpetArea: 2000,
    furnishing: 'furnished',
    ageOfProperty: '3 years',
    possessionStatus: 'ready',
    locality: 'Guindy',
    city: 'Chennai',
    state: 'Tamil Nadu',
    address: 'SIDCO Industrial Estate, Guindy, Chennai - 600032',
    lat: 13.0085,
    lng: 80.2154,
    images: [img(4), img(5), img(0)],
    amenities: ['ac', 'lift', 'power-backup', 'cctv', 'parking', 'fire-safety', 'intercom', 'wifi'],
    verified: true,
    reraRegistered: false,
    directFromOwner: false,
    ownerId: 'owner-017',
    ownerName: 'Commercial Spaces India',
    ownerPhone: '+91 99567 89012',
    views: 1345,
    createdAt: '2024-09-18T10:00:00.000Z',
    updatedAt: '2024-12-18T12:00:00.000Z',
  },
  {
    id: 'list-018',
    title: 'Retail Shop in T Nagar – High Footfall Area',
    description:
      'Prime retail shop space in the busiest commercial area of T Nagar. Located on the ground floor of a commercial complex. Excellent for retail stores, restaurants, or showrooms. High footfall guaranteed.',
    category: 'commercial',
    propertyType: 'commercial-shop',
    price: 120000,
    priceLabel: '₹1.2 Lakh/month',
    deposit: 480000,
    bhk: 0,
    bathrooms: 1,
    balconies: 0,
    floor: 'Ground',
    totalFloors: 4,
    carpetArea: 650,
    furnishing: 'unfurnished',
    ageOfProperty: '5 years',
    possessionStatus: 'ready',
    locality: 'T Nagar',
    city: 'Chennai',
    state: 'Tamil Nadu',
    address: 'Ranganathan Street, T Nagar, Chennai - 600017',
    lat: 13.0432,
    lng: 80.2318,
    images: [img(5), img(0), img(1)],
    amenities: ['power-backup', 'cctv', 'parking', 'water-supply'],
    verified: false,
    reraRegistered: false,
    directFromOwner: true,
    ownerId: 'owner-018',
    ownerName: 'Meenakshi Sundaram',
    ownerPhone: '+91 99678 90123',
    views: 2567,
    createdAt: '2024-10-02T11:00:00.000Z',
    updatedAt: '2024-12-21T15:00:00.000Z',
  },
];

// ─── MOCK LEADS ──────────────────────────────────────────────────────

export const mockLeads: Lead[] = [
  {
    id: 'lead-001',
    listingId: 'list-001',
    listingTitle: 'Spacious 2 BHK Apartment in Anna Nagar',
    buyerName: 'Arun Vijay',
    buyerPhone: '+91 98700 11223',
    buyerEmail: 'arun.vijay@email.com',
    message:
      'Hi, I am interested in this 2 BHK apartment. Is it available for immediate site visit? Also, please share the maintenance charges and car parking details.',
    status: 'hot',
    createdAt: '2024-12-18T09:30:00.000Z',
  },
  {
    id: 'lead-002',
    listingId: 'list-002',
    listingTitle: 'Luxury 3 BHK Flat at OMR with Sea View',
    buyerName: 'Divya Krishnan',
    buyerPhone: '+91 98700 44556',
    buyerEmail: 'divya.k@email.com',
    message:
      'Looking for a 3 BHK near OMR IT corridor. Would like to schedule a visit this weekend. What is the EMI option available?',
    status: 'hot',
    createdAt: '2024-12-19T14:15:00.000Z',
  },
  {
    id: 'lead-003',
    listingId: 'list-013',
    listingTitle: '2 BHK Flat for Rent in Anna Nagar',
    buyerName: 'Rohit Mehta',
    buyerPhone: '+91 98700 77889',
    message:
      'Need a 2 BHK on rent in Anna Nagar for a family of 3. Is this pet-friendly? What is the lease duration and lock-in period?',
    status: 'warm',
    createdAt: '2024-12-20T11:00:00.000Z',
  },
  {
    id: 'lead-004',
    listingId: 'list-009',
    listingTitle: 'Independent 4 BHK Villa in ECR',
    buyerName: 'Sanjay Patel',
    buyerPhone: '+91 98700 99001',
    buyerEmail: 'sanjay.patel@email.com',
    message:
      'I am a NRI interested in this villa for investment. Can you provide a video tour? Also, what is the resale potential in this area?',
    status: 'warm',
    createdAt: '2024-12-21T16:45:00.000Z',
  },
  {
    id: 'lead-005',
    listingId: 'list-017',
    listingTitle: 'Commercial Office Space in Guindy – 2000 sqft',
    buyerName: 'Priya Chandrasekaran',
    buyerPhone: '+91 98700 22334',
    buyerEmail: 'priya.cs@startup.com',
    message:
      'We are a 15-member startup looking for office space. Is there scope for expansion? What are the terms for a 3-year lease?',
    status: 'cold',
    createdAt: '2024-12-22T08:30:00.000Z',
  },
];

// ─── MOCK PRICE TRENDS ───────────────────────────────────────────────

export const mockPriceTrends: Record<string, PriceTrend[]> = {
  'Anna Nagar': [
    { month: 'Jan', price: 6200 },
    { month: 'Feb', price: 6250 },
    { month: 'Mar', price: 6300 },
    { month: 'Apr', price: 6280 },
    { month: 'May', price: 6400 },
    { month: 'Jun', price: 6500 },
    { month: 'Jul', price: 6550 },
    { month: 'Aug', price: 6700 },
    { month: 'Sep', price: 6850 },
    { month: 'Oct', price: 7000 },
    { month: 'Nov', price: 7150 },
    { month: 'Dec', price: 7350 },
  ],
  OMR: [
    { month: 'Jan', price: 5500 },
    { month: 'Feb', price: 5520 },
    { month: 'Mar', price: 5580 },
    { month: 'Apr', price: 5600 },
    { month: 'May', price: 5650 },
    { month: 'Jun', price: 5700 },
    { month: 'Jul', price: 5720 },
    { month: 'Aug', price: 5780 },
    { month: 'Sep', price: 5850 },
    { month: 'Oct', price: 5900 },
    { month: 'Nov', price: 6000 },
    { month: 'Dec', price: 6100 },
  ],
  Velachery: [
    { month: 'Jan', price: 5800 },
    { month: 'Feb', price: 5850 },
    { month: 'Mar', price: 5820 },
    { month: 'Apr', price: 5900 },
    { month: 'May', price: 5950 },
    { month: 'Jun', price: 6000 },
    { month: 'Jul', price: 6050 },
    { month: 'Aug', price: 6100 },
    { month: 'Sep', price: 6150 },
    { month: 'Oct', price: 6200 },
    { month: 'Nov', price: 6300 },
    { month: 'Dec', price: 6400 },
  ],
};

// ─── MOCK LOCALITY INSIGHTS ─────────────────────────────────────────

export const mockLocalityInsights: Record<string, LocalityInsight> = {
  'Anna Nagar': {
    safety: 4.5,
    connectivity: 4.0,
    infrastructure: 4.5,
    airQuality: 3.5,
    nightlife: 3.5,
    restaurants: 4.0,
  },
  OMR: {
    safety: 4.0,
    connectivity: 3.5,
    infrastructure: 4.0,
    airQuality: 4.0,
    nightlife: 3.0,
    restaurants: 3.5,
  },
  Velachery: {
    safety: 4.0,
    connectivity: 4.5,
    infrastructure: 4.0,
    airQuality: 3.0,
    nightlife: 4.0,
    restaurants: 4.5,
  },
};

// ═══════════════════════════════════════════════════════════════════════
// SECTION A: EXTENDED PROPERTIES (list-019 through list-050) — 32 NEW LISTINGS
// ═══════════════════════════════════════════════════════════════════════

// We push new properties via a separate array so the original export stays untouched.
export const mockListingsExtended: PropertyListing[] = [
  // ─── BUY MUMBAI (5) ────────────────────────────────────────────────
  {
    id: 'list-019',
    title: 'Elegant 2 BHK Apartment in Bandra West',
    description:
      'Premium 2 BHK apartment in the upscale Bandra West locality. Walking distance to Linking Road, Hill Road, and Bandra Bandstand. Fully renovated with modern fittings and vitrified tiles. Gated society with 24/7 security.',
    category: 'buy',
    propertyType: 'apartment',
    price: 12000000,
    priceLabel: '₹1.2 Cr',
    originalPrice: 13500000,
    bhk: 2,
    bathrooms: 2,
    balconies: 1,
    floor: '7th of 14',
    totalFloors: 14,
    carpetArea: 850,
    furnishing: 'semifurnished',
    ageOfProperty: '5 years',
    possessionStatus: 'ready',
    locality: 'Bandra',
    city: 'Mumbai',
    state: 'Maharashtra',
    address: 'Mount Mary Road, Bandra West, Mumbai - 400050',
    lat: 19.0596,
    lng: 72.8295,
    images: [img(0), img(1), img(2)],
    amenities: ['parking', 'security', 'lift', 'power-backup', 'garden', 'cctv', 'intercom'],
    verified: true,
    reraRegistered: true,
    reraId: 'MH/RERA/P5200/2023',
    directFromOwner: false,
    ownerId: 'owner-019',
    ownerName: 'Rustomjee Builders',
    ownerPhone: '+91 98100 12345',
    views: 3456,
    createdAt: '2024-10-12T09:00:00.000Z',
    updatedAt: '2024-12-20T14:00:00.000Z',
  },
  {
    id: 'list-020',
    title: 'Spacious 3 BHK in Andheri East – Near Metro',
    description:
      'Well-designed 3 BHK apartment in Andheri East, close to Andheri metro station and Saki Naka. Ideal for families working in MIDC and Andheri Kurla Road. Ample parking, children play area, and jogging track.',
    category: 'buy',
    propertyType: 'apartment',
    price: 18000000,
    priceLabel: '₹1.8 Cr',
    bhk: 3,
    bathrooms: 3,
    balconies: 2,
    floor: '11th of 20',
    totalFloors: 20,
    carpetArea: 1350,
    furnishing: 'unfurnished',
    ageOfProperty: '3 years',
    possessionStatus: 'ready',
    locality: 'Andheri',
    city: 'Mumbai',
    state: 'Maharashtra',
    address: 'Chandivali Farm Road, Andheri East, Mumbai - 400072',
    lat: 19.1197,
    lng: 72.8464,
    images: [img(1), img(2), img(3)],
    amenities: ['parking', 'gym', 'security', 'lift', 'power-backup', 'children-play', 'jogging-track', 'cctv'],
    verified: true,
    reraRegistered: true,
    reraId: 'MH/RERA/P5201/2023',
    directFromOwner: false,
    ownerId: 'owner-020',
    ownerName: 'Lodha Group',
    ownerPhone: '+91 98200 23456',
    views: 2890,
    createdAt: '2024-09-05T11:00:00.000Z',
    updatedAt: '2024-12-19T10:00:00.000Z',
  },
  {
    id: 'list-021',
    title: 'Luxury 4 BHK Villa in Powai Lake View',
    description:
      'Magnificent 4 BHK villa overlooking Powai Lake. Independent house with private garden, terrace, and servant quarters. Italian marble flooring, modular kitchen, and smart home automation. Ultra-premium gated community.',
    category: 'buy',
    propertyType: 'villa',
    price: 35000000,
    priceLabel: '₹3.5 Cr',
    originalPrice: 39000000,
    bhk: 4,
    bathrooms: 4,
    balconies: 2,
    floor: 'Ground + 2',
    totalFloors: 3,
    carpetArea: 2800,
    superBuiltUpArea: 3200,
    plotArea: 3000,
    furnishing: 'furnished',
    ageOfProperty: '2 years',
    possessionStatus: 'ready',
    locality: 'Powai',
    city: 'Mumbai',
    state: 'Maharashtra',
    address: 'Hiranandani Gardens, Powai, Mumbai - 400076',
    lat: 19.1278,
    lng: 72.9058,
    images: [img(2), img(3), img(4)],
    amenities: ['parking', 'gym', 'pool', 'security', 'garden', 'power-backup', 'clubhouse', 'cctv', 'vaastu', 'servant-room', 'jogging-track'],
    verified: true,
    reraRegistered: true,
    reraId: 'MH/RERA/P5202/2024',
    directFromOwner: true,
    ownerId: 'owner-021',
    ownerName: 'Hiranandani Communities',
    ownerPhone: '+91 98300 34567',
    views: 5670,
    createdAt: '2024-08-15T12:00:00.000Z',
    updatedAt: '2024-12-21T16:00:00.000Z',
  },
  {
    id: 'list-022',
    title: 'Ultra-Luxury 3 BHK in Worli Sea Face',
    description:
      'Exquisite 3 BHK apartment on Worli Sea Face with panoramic Arabian Sea views. Floor-to-ceiling windows, imported Italian fittings, and designer interiors. Premium tower with concierge services, spa, and infinity pool.',
    category: 'buy',
    propertyType: 'apartment',
    price: 42000000,
    priceLabel: '₹4.2 Cr',
    bhk: 3,
    bathrooms: 3,
    balconies: 2,
    floor: '22nd of 35',
    totalFloors: 35,
    carpetArea: 1800,
    superBuiltUpArea: 2200,
    furnishing: 'furnished',
    ageOfProperty: 'New Launch',
    possessionStatus: 'ready',
    locality: 'Worli',
    city: 'Mumbai',
    state: 'Maharashtra',
    address: 'Vivek Khand, Worli Sea Face, Mumbai - 400030',
    lat: 19.0180,
    lng: 72.8435,
    images: [img(3), img(4), img(5)],
    amenities: ['parking', 'gym', 'pool', 'security', 'lift', 'power-backup', 'clubhouse', 'cctv', 'intercom', 'ac', 'vaastu', 'servant-room', 'wifi'],
    verified: true,
    reraRegistered: true,
    reraId: 'MH/RERA/P5203/2024',
    directFromOwner: false,
    ownerId: 'owner-022',
    ownerName: 'Oberoi Realty',
    ownerPhone: '+91 98400 45678',
    views: 7890,
    createdAt: '2024-07-20T10:00:00.000Z',
    updatedAt: '2024-12-22T08:00:00.000Z',
  },
  {
    id: 'list-023',
    title: 'Modern 2 BHK Flat in Juhu – Near Beach',
    description:
      'Stylish 2 BHK apartment in Juhu, just 500 meters from Juhu Beach. Open kitchen concept, wooden flooring in bedrooms, and a spacious balcony with sea breeze. Well-connected to SV Road and Western Express Highway.',
    category: 'buy',
    propertyType: 'apartment',
    price: 9500000,
    priceLabel: '₹95 Lakhs',
    originalPrice: 10500000,
    bhk: 2,
    bathrooms: 2,
    balconies: 1,
    floor: '4th of 8',
    totalFloors: 8,
    carpetArea: 780,
    furnishing: 'semifurnished',
    ageOfProperty: '4 years',
    possessionStatus: 'ready',
    locality: 'Juhu',
    city: 'Mumbai',
    state: 'Maharashtra',
    address: 'Juhu Tara Road, Juhu, Mumbai - 400049',
    lat: 19.0982,
    lng: 72.8263,
    images: [img(4), img(5), img(0)],
    amenities: ['parking', 'security', 'lift', 'power-backup', 'garden', 'cctv'],
    verified: true,
    reraRegistered: true,
    reraId: 'MH/RERA/P5204/2023',
    directFromOwner: true,
    ownerId: 'owner-023',
    ownerName: 'Sanjay Kapoor',
    ownerPhone: '+91 98500 56789',
    views: 2340,
    createdAt: '2024-11-01T08:30:00.000Z',
    updatedAt: '2024-12-20T11:00:00.000Z',
  },

  // ─── BUY DELHI (5) ─────────────────────────────────────────────────
  {
    id: 'list-024',
    title: '3 BHK Apartment in Dwarka Sector 23',
    description:
      'Spacious 3 BHK apartment in Dwarka Sector 23, near Dwarka Sec 21 Metro. Well-planned DDA society with lush green parks, community centre, and market complex. Excellent connectivity to IGI Airport and Gurgaon.',
    category: 'buy',
    propertyType: 'apartment',
    price: 8500000,
    priceLabel: '₹85 Lakhs',
    bhk: 3,
    bathrooms: 3,
    balconies: 2,
    floor: '6th of 12',
    totalFloors: 12,
    carpetArea: 1200,
    furnishing: 'semifurnished',
    ageOfProperty: '4 years',
    possessionStatus: 'ready',
    locality: 'Dwarka',
    city: 'Delhi',
    state: 'Delhi',
    address: 'Plot 5, Sector 23, Dwarka, New Delhi - 110075',
    lat: 28.5733,
    lng: 77.0725,
    images: [img(5), img(0), img(1)],
    amenities: ['parking', 'security', 'lift', 'power-backup', 'garden', 'children-play', 'cctv'],
    verified: true,
    reraRegistered: true,
    reraId: 'DLRERA/2023/PRJ/1234',
    directFromOwner: false,
    ownerId: 'owner-024',
    ownerName: 'DDA Housing Society',
    ownerPhone: '+91 98110 67890',
    views: 1890,
    createdAt: '2024-10-08T09:00:00.000Z',
    updatedAt: '2024-12-18T13:00:00.000Z',
  },
  {
    id: 'list-025',
    title: 'Affordable 2 BHK in Rohini Sector 7',
    description:
      'Budget-friendly 2 BHK apartment in Rohini Sector 7, near Rithala Metro. Well-maintained CGHS society with 24/7 security and power backup. Close to schools, hospitals, and shopping malls. Ideal for first-time buyers.',
    category: 'buy',
    propertyType: 'apartment',
    price: 6500000,
    priceLabel: '₹65 Lakhs',
    bhk: 2,
    bathrooms: 2,
    balconies: 1,
    floor: '3rd of 7',
    totalFloors: 7,
    carpetArea: 850,
    furnishing: 'unfurnished',
    ageOfProperty: '6 years',
    possessionStatus: 'ready',
    locality: 'Rohini',
    city: 'Delhi',
    state: 'Delhi',
    address: 'Pocket 3, Sector 7, Rohini, New Delhi - 110085',
    lat: 28.7321,
    lng: 77.1162,
    images: [img(0), img(1), img(2)],
    amenities: ['parking', 'security', 'lift', 'power-backup', 'water-supply'],
    verified: true,
    reraRegistered: false,
    directFromOwner: true,
    ownerId: 'owner-025',
    ownerName: 'Arun Sharma',
    ownerPhone: '+91 98210 78901',
    views: 1230,
    createdAt: '2024-11-15T10:00:00.000Z',
    updatedAt: '2024-12-21T09:00:00.000Z',
  },
  {
    id: 'list-026',
    title: 'Premium 4 BHK in Vasant Kunj Enclave',
    description:
      'Luxurious 4 BHK apartment in the prestigious Vasant Kunj Enclave. Close to Vasant Square Mall, Embassies, and Jawaharlal Nehru University. Italian marble flooring, modular kitchen, and smart home features.',
    category: 'buy',
    propertyType: 'apartment',
    price: 25000000,
    priceLabel: '₹2.5 Cr',
    originalPrice: 28000000,
    bhk: 4,
    bathrooms: 4,
    balconies: 3,
    floor: '9th of 16',
    totalFloors: 16,
    carpetArea: 2200,
    superBuiltUpArea: 2600,
    furnishing: 'furnished',
    ageOfProperty: '2 years',
    possessionStatus: 'ready',
    locality: 'Vasant Kunj',
    city: 'Delhi',
    state: 'Delhi',
    address: 'Enclave Part 2, Vasant Kunj, New Delhi - 110070',
    lat: 28.5268,
    lng: 77.1548,
    images: [img(1), img(2), img(3)],
    amenities: ['parking', 'gym', 'pool', 'security', 'lift', 'power-backup', 'clubhouse', 'cctv', 'vaastu', 'servant-room', 'intercom'],
    verified: true,
    reraRegistered: true,
    reraId: 'DLRERA/2024/PRJ/5678',
    directFromOwner: false,
    ownerId: 'owner-026',
    ownerName: 'Raheja Developers',
    ownerPhone: '+91 98310 89012',
    views: 3450,
    createdAt: '2024-09-01T11:00:00.000Z',
    updatedAt: '2024-12-20T15:00:00.000Z',
  },
  {
    id: 'list-027',
    title: '3 BHK Flat in Saket – Near Select Citywalk',
    description:
      'Well-located 3 BHK flat in Saket, walking distance to Select Citywalk Mall and Max Hospital. Lush green surroundings with excellent connectivity via Metro and buses. Gated society with modern amenities.',
    category: 'buy',
    propertyType: 'apartment',
    price: 15000000,
    priceLabel: '₹1.5 Cr',
    bhk: 3,
    bathrooms: 3,
    balconies: 2,
    floor: '5th of 10',
    totalFloors: 10,
    carpetArea: 1400,
    furnishing: 'semifurnished',
    ageOfProperty: '5 years',
    possessionStatus: 'ready',
    locality: 'Saket',
    city: 'Delhi',
    state: 'Delhi',
    address: 'A-Block, Pushp Vihar, Saket, New Delhi - 110017',
    lat: 28.5245,
    lng: 77.2066,
    images: [img(2), img(3), img(4)],
    amenities: ['parking', 'gym', 'security', 'lift', 'power-backup', 'garden', 'children-play', 'intercom'],
    verified: true,
    reraRegistered: true,
    reraId: 'DLRERA/2023/PRJ/9012',
    directFromOwner: false,
    ownerId: 'owner-027',
    ownerName: 'Emaar India',
    ownerPhone: '+91 98410 90123',
    views: 2670,
    createdAt: '2024-10-25T08:00:00.000Z',
    updatedAt: '2024-12-19T12:00:00.000Z',
  },
  {
    id: 'list-028',
    title: '2 BHK in Rajouri Garden – Well Connected',
    description:
      'Compact 2 BHK apartment in Rajouri Garden, right on the Pink Line Metro. Proximity to Pacific Mall, Tagore Garden, and Jhandewalan. Good investment with high rental yield. Well-ventilated with 3-side open.',
    category: 'buy',
    propertyType: 'apartment',
    price: 7200000,
    priceLabel: '₹72 Lakhs',
    originalPrice: 8000000,
    bhk: 2,
    bathrooms: 2,
    balconies: 1,
    floor: '4th of 8',
    totalFloors: 8,
    carpetArea: 820,
    furnishing: 'unfurnished',
    ageOfProperty: '7 years',
    possessionStatus: 'ready',
    locality: 'Rajouri Garden',
    city: 'Delhi',
    state: 'Delhi',
    address: 'J-Block, Rajouri Garden, New Delhi - 110027',
    lat: 28.6519,
    lng: 77.1167,
    images: [img(3), img(4), img(5)],
    amenities: ['parking', 'security', 'lift', 'power-backup', 'water-supply'],
    verified: true,
    reraRegistered: false,
    directFromOwner: true,
    ownerId: 'owner-028',
    ownerName: 'Manish Gupta',
    ownerPhone: '+91 98510 01234',
    views: 1450,
    createdAt: '2024-11-20T10:30:00.000Z',
    updatedAt: '2024-12-22T07:00:00.000Z',
  },

  // ─── BUY BANGALORE (4) ─────────────────────────────────────────────
  {
    id: 'list-029',
    title: '3 BHK in Whitefield – IT Corridor',
    description:
      'Modern 3 BHK apartment in Whitefield, near ITPL and Forum Shantiniketan Mall. Well-ventilated with large balconies overlooking a green canopy. Perfect for IT professionals. Gated community with clubhouse.',
    category: 'buy',
    propertyType: 'apartment',
    price: 8500000,
    priceLabel: '₹85 Lakhs',
    bhk: 3,
    bathrooms: 3,
    balconies: 2,
    floor: '8th of 18',
    totalFloors: 18,
    carpetArea: 1450,
    furnishing: 'semifurnished',
    ageOfProperty: '3 years',
    possessionStatus: 'ready',
    locality: 'Whitefield',
    city: 'Bangalore',
    state: 'Karnataka',
    address: 'Prestige Shantiniketan, Whitefield, Bangalore - 560066',
    lat: 12.9698,
    lng: 77.7500,
    images: [img(4), img(5), img(0)],
    amenities: ['parking', 'gym', 'pool', 'security', 'lift', 'power-backup', 'clubhouse', 'jogging-track', 'children-play', 'cctv'],
    verified: true,
    reraRegistered: true,
    reraId: 'RERA/PRM/KA/RERA/1234/2023',
    directFromOwner: false,
    ownerId: 'owner-029',
    ownerName: 'Prestige Estates',
    ownerPhone: '+91 98120 11223',
    views: 3120,
    createdAt: '2024-09-15T09:00:00.000Z',
    updatedAt: '2024-12-20T10:00:00.000Z',
  },
  {
    id: 'list-030',
    title: 'Luxury 2 BHK in Koramangala 4th Block',
    description:
      'Trendy 2 BHK apartment in the heart of Koramangala. Surrounded by cafes, restaurants, and co-working spaces. Designer interiors with wooden flooring and a fully equipped modular kitchen. Walk to Forum Mall.',
    category: 'buy',
    propertyType: 'apartment',
    price: 12000000,
    priceLabel: '₹1.2 Cr',
    bhk: 2,
    bathrooms: 2,
    balconies: 1,
    floor: '6th of 10',
    totalFloors: 10,
    carpetArea: 1100,
    furnishing: 'furnished',
    ageOfProperty: '2 years',
    possessionStatus: 'ready',
    locality: 'Koramangala',
    city: 'Bangalore',
    state: 'Karnataka',
    address: '4th Block, 80 Feet Road, Koramangala, Bangalore - 560034',
    lat: 12.9352,
    lng: 77.6245,
    images: [img(5), img(0), img(1)],
    amenities: ['parking', 'gym', 'security', 'lift', 'power-backup', 'intercom', 'cctv', 'vaastu'],
    verified: true,
    reraRegistered: true,
    reraId: 'RERA/PRM/KA/RERA/5678/2024',
    directFromOwner: true,
    ownerId: 'owner-030',
    ownerName: 'Nisha Reddy',
    ownerPhone: '+91 98230 22334',
    views: 4560,
    createdAt: '2024-08-20T11:00:00.000Z',
    updatedAt: '2024-12-19T14:00:00.000Z',
  },
  {
    id: 'list-031',
    title: 'Premium 3 BHK in HSR Layout Sector 2',
    description:
      'Premium 3 BHK in HSR Layout, one of Bangalore\'s most sought-after residential areas. Near the famous HSR Layout food street and tech parks. Smart home features, large balcony with city view.',
    category: 'buy',
    propertyType: 'apartment',
    price: 15000000,
    priceLabel: '₹1.5 Cr',
    originalPrice: 17000000,
    bhk: 3,
    bathrooms: 3,
    balconies: 2,
    floor: '12th of 20',
    totalFloors: 20,
    carpetArea: 1600,
    furnishing: 'furnished',
    ageOfProperty: '1 year',
    possessionStatus: 'ready',
    locality: 'HSR Layout',
    city: 'Bangalore',
    state: 'Karnataka',
    address: 'Sector 2, 27th Main, HSR Layout, Bangalore - 560102',
    lat: 12.9116,
    lng: 77.6389,
    images: [img(0), img(1), img(2)],
    amenities: ['parking', 'gym', 'pool', 'security', 'lift', 'power-backup', 'clubhouse', 'cctv', 'intercom', 'ac', 'vaastu', 'wifi'],
    verified: true,
    reraRegistered: true,
    reraId: 'RERA/PRM/KA/RERA/9012/2024',
    directFromOwner: false,
    ownerId: 'owner-031',
    ownerName: 'Brigade Group',
    ownerPhone: '+91 98340 33445',
    views: 3890,
    createdAt: '2024-07-10T12:00:00.000Z',
    updatedAt: '2024-12-21T16:00:00.000Z',
  },
  {
    id: 'list-032',
    title: 'Affordable 2 BHK in Electronic City Phase 1',
    description:
      'Compact and well-designed 2 BHK in Electronic City Phase 1. Walking distance to Infosys, Wipro, and other tech campuses. Budget-friendly with all essential amenities. Excellent for IT professionals.',
    category: 'buy',
    propertyType: 'apartment',
    price: 5200000,
    priceLabel: '₹52 Lakhs',
    bhk: 2,
    bathrooms: 2,
    balconies: 1,
    floor: '5th of 12',
    totalFloors: 12,
    carpetArea: 950,
    furnishing: 'unfurnished',
    ageOfProperty: '5 years',
    possessionStatus: 'ready',
    locality: 'Electronic City',
    city: 'Bangalore',
    state: 'Karnataka',
    address: 'Phase 1, Electronic City, Bangalore - 560100',
    lat: 12.8441,
    lng: 77.6731,
    images: [img(1), img(2), img(3)],
    amenities: ['parking', 'security', 'lift', 'power-backup', 'garden', 'children-play'],
    verified: true,
    reraRegistered: true,
    reraId: 'RERA/PRM/KA/RERA/3456/2023',
    directFromOwner: false,
    ownerId: 'owner-032',
    ownerName: 'Sobha Limited',
    ownerPhone: '+91 98450 44556',
    views: 2100,
    createdAt: '2024-10-01T10:00:00.000Z',
    updatedAt: '2024-12-18T11:00:00.000Z',
  },

  // ─── BUY HYDERABAD (3) ─────────────────────────────────────────────
  {
    id: 'list-033',
    title: 'Luxury 3 BHK in Gachibowli – Financial District',
    description:
      'Premium 3 BHK apartment in Gachibowli, the financial and IT hub of Hyderabad. Walking distance to Microsoft, Amazon, and ICICI Bank campuses. Clubhouse, swimming pool, and landscaped gardens.',
    category: 'buy',
    propertyType: 'apartment',
    price: 12000000,
    priceLabel: '₹1.2 Cr',
    bhk: 3,
    bathrooms: 3,
    balconies: 2,
    floor: '15th of 25',
    totalFloors: 25,
    carpetArea: 1650,
    furnishing: 'semifurnished',
    ageOfProperty: '2 years',
    possessionStatus: 'ready',
    locality: 'Gachibowli',
    city: 'Hyderabad',
    state: 'Telangana',
    address: 'My Home Bhooja, Gachibowli, Hyderabad - 500032',
    lat: 17.4401,
    lng: 78.3489,
    images: [img(2), img(3), img(4)],
    amenities: ['parking', 'gym', 'pool', 'security', 'lift', 'power-backup', 'clubhouse', 'jogging-track', 'children-play', 'cctv', 'intercom'],
    verified: true,
    reraRegistered: true,
    reraId: 'TS/RERA/P024/2023',
    directFromOwner: false,
    ownerId: 'owner-033',
    ownerName: 'My Home Constructions',
    ownerPhone: '+91 98160 55667',
    views: 3780,
    createdAt: '2024-09-10T09:00:00.000Z',
    updatedAt: '2024-12-20T12:00:00.000Z',
  },
  {
    id: 'list-034',
    title: '2 BHK in Madhapur – Near HITEC City',
    description:
      'Well-located 2 BHK in Madhapur, adjacent to HITEC City and Kavuri Hills. Close to Inorbit Mall and Cyber Towers. Modern amenities with a vibrant neighbourhood. Good for young professionals and couples.',
    category: 'buy',
    propertyType: 'apartment',
    price: 7200000,
    priceLabel: '₹72 Lakhs',
    bhk: 2,
    bathrooms: 2,
    balconies: 1,
    floor: '7th of 14',
    totalFloors: 14,
    carpetArea: 1050,
    furnishing: 'semifurnished',
    ageOfProperty: '3 years',
    possessionStatus: 'ready',
    locality: 'Madhapur',
    city: 'Hyderabad',
    state: 'Telangana',
    address: 'Kavuri Hills, Madhapur, Hyderabad - 500081',
    lat: 17.4498,
    lng: 78.3918,
    images: [img(3), img(4), img(5)],
    amenities: ['parking', 'gym', 'security', 'lift', 'power-backup', 'cctv', 'intercom'],
    verified: true,
    reraRegistered: true,
    reraId: 'TS/RERA/P025/2023',
    directFromOwner: true,
    ownerId: 'owner-034',
    ownerName: 'Rajesh Verma',
    ownerPhone: '+91 98270 66778',
    views: 2340,
    createdAt: '2024-10-18T10:30:00.000Z',
    updatedAt: '2024-12-19T09:00:00.000Z',
  },
  {
    id: 'list-035',
    title: 'Ultra-Luxury 4 BHK Villa in Jubilee Hills',
    description:
      'Magnificent 4 BHK independent villa in the prestigious Jubilee Hills. Road No. 36 address with private garden, swimming pool, and home theatre. Italian marble, B&B Italia furniture, and Crestron smart home.',
    category: 'buy',
    propertyType: 'villa',
    price: 25000000,
    priceLabel: '₹2.5 Cr',
    originalPrice: 28000000,
    bhk: 4,
    bathrooms: 5,
    balconies: 2,
    floor: 'Ground + 2',
    totalFloors: 3,
    carpetArea: 3500,
    superBuiltUpArea: 4000,
    plotArea: 500,
    furnishing: 'furnished',
    ageOfProperty: '1 year',
    possessionStatus: 'ready',
    locality: 'Jubilee Hills',
    city: 'Hyderabad',
    state: 'Telangana',
    address: 'Road No. 36, Jubilee Hills, Hyderabad - 500033',
    lat: 17.4156,
    lng: 78.4065,
    images: [img(4), img(5), img(0)],
    amenities: ['parking', 'gym', 'pool', 'security', 'garden', 'power-backup', 'cctv', 'vaastu', 'servant-room', 'fire-safety', 'ac', 'wifi'],
    verified: true,
    reraRegistered: true,
    reraId: 'TS/RERA/P026/2024',
    directFromOwner: true,
    ownerId: 'owner-035',
    ownerName: 'Suresh Babu',
    ownerPhone: '+91 98380 77889',
    views: 5670,
    createdAt: '2024-08-05T11:00:00.000Z',
    updatedAt: '2024-12-22T10:00:00.000Z',
  },

  // ─── RENT PUNE (3) ─────────────────────────────────────────────────
  {
    id: 'list-036',
    title: '2 BHK for Rent in Hinjewadi Phase 1',
    description:
      'Well-maintained 2 BHK apartment for rent in Hinjewadi Phase 1. Walking distance to IT parks and tech campuses. Semi-furnished with wardrobe, geyser, and fans. Ideal for IT professionals and families.',
    category: 'rent',
    propertyType: 'apartment',
    price: 25000,
    priceLabel: '₹25,000/month',
    deposit: 100000,
    bhk: 2,
    bathrooms: 2,
    balconies: 1,
    floor: '6th of 10',
    totalFloors: 10,
    carpetArea: 950,
    furnishing: 'semifurnished',
    ageOfProperty: '3 years',
    possessionStatus: 'ready',
    locality: 'Hinjewadi',
    city: 'Pune',
    state: 'Maharashtra',
    address: 'Phase 1, Hinjewadi, Pune - 411057',
    lat: 18.5921,
    lng: 73.7392,
    images: [img(5), img(0), img(1)],
    amenities: ['parking', 'security', 'lift', 'power-backup', 'water-supply'],
    verified: true,
    reraRegistered: false,
    directFromOwner: false,
    ownerId: 'owner-036',
    ownerName: 'Pune Rental Homes',
    ownerPhone: '+91 98190 88990',
    views: 1340,
    createdAt: '2024-12-01T09:00:00.000Z',
    updatedAt: '2024-12-22T08:00:00.000Z',
  },
  {
    id: 'list-037',
    title: '1 BHK for Rent in Wakad – Near Highway',
    description:
      'Compact 1 BHK in Wakad near Mumbai-Pune highway and D-Mart. Freshly painted with basic furniture including bed and sofa. Society has garden and children play area. Good connectivity to Hinjewadi and Baner.',
    category: 'rent',
    propertyType: 'apartment',
    price: 15000,
    priceLabel: '₹15,000/month',
    deposit: 60000,
    bhk: 1,
    bathrooms: 1,
    balconies: 1,
    floor: '3rd of 7',
    totalFloors: 7,
    carpetArea: 550,
    furnishing: 'semifurnished',
    ageOfProperty: '4 years',
    possessionStatus: 'ready',
    locality: 'Wakad',
    city: 'Pune',
    state: 'Maharashtra',
    address: 'Datta Mandir Road, Wakad, Pune - 411057',
    lat: 18.5539,
    lng: 73.7685,
    images: [img(0), img(1), img(2)],
    amenities: ['parking', 'power-backup', 'water-supply', 'garden'],
    verified: false,
    reraRegistered: false,
    directFromOwner: true,
    ownerId: 'owner-037',
    ownerName: 'Preeti Deshmukh',
    ownerPhone: '+91 98280 99001',
    views: 890,
    createdAt: '2024-12-05T11:00:00.000Z',
    updatedAt: '2024-12-21T14:00:00.000Z',
  },
  {
    id: 'list-038',
    title: '3 BHK for Rent in Baner – Fully Furnished',
    description:
      'Spacious fully furnished 3 BHK in upscale Baner. Comes with AC, washing machine, refrigerator, microwave, and modular kitchen. Close to Balewadi High Street and Pune University. Covered parking for 2 cars.',
    category: 'rent',
    propertyType: 'apartment',
    price: 38000,
    priceLabel: '₹38,000/month',
    deposit: 152000,
    bhk: 3,
    bathrooms: 3,
    balconies: 2,
    floor: '8th of 12',
    totalFloors: 12,
    carpetArea: 1400,
    furnishing: 'furnished',
    ageOfProperty: '2 years',
    possessionStatus: 'ready',
    locality: 'Baner',
    city: 'Pune',
    state: 'Maharashtra',
    address: 'Baner Road, Baner, Pune - 411045',
    lat: 18.5573,
    lng: 73.8077,
    images: [img(1), img(2), img(3)],
    amenities: ['parking', 'gym', 'security', 'lift', 'power-backup', 'clubhouse', 'cctv', 'intercom'],
    verified: true,
    reraRegistered: false,
    directFromOwner: false,
    ownerId: 'owner-038',
    ownerName: 'NoBroker Property Manager',
    ownerPhone: '+91 98370 00112',
    views: 1780,
    createdAt: '2024-11-10T10:00:00.000Z',
    updatedAt: '2024-12-20T11:00:00.000Z',
  },

  // ─── RENT KOLKATA (3) ──────────────────────────────────────────────
  {
    id: 'list-039',
    title: '2 BHK for Rent in Salt Lake Sector V',
    description:
      'Well-ventilated 2 BHK in Salt Lake Sector V, the IT hub of Kolkata. Walking distance to Tech Park and major software companies. Near City Centre mall and Salt Lake Stadium. Freshly renovated.',
    category: 'rent',
    propertyType: 'apartment',
    price: 18000,
    priceLabel: '₹18,000/month',
    deposit: 72000,
    bhk: 2,
    bathrooms: 2,
    balconies: 1,
    floor: '5th of 8',
    totalFloors: 8,
    carpetArea: 900,
    furnishing: 'semifurnished',
    ageOfProperty: '6 years',
    possessionStatus: 'ready',
    locality: 'Salt Lake',
    city: 'Kolkata',
    state: 'West Bengal',
    address: 'Block EP, Sector V, Salt Lake, Kolkata - 700091',
    lat: 22.5726,
    lng: 88.4010,
    images: [img(2), img(3), img(4)],
    amenities: ['parking', 'security', 'lift', 'power-backup', 'water-supply'],
    verified: true,
    reraRegistered: false,
    directFromOwner: true,
    ownerId: 'owner-039',
    ownerName: 'Amitava Banerjee',
    ownerPhone: '+91 98140 11223',
    views: 1120,
    createdAt: '2024-11-25T09:00:00.000Z',
    updatedAt: '2024-12-21T10:00:00.000Z',
  },
  {
    id: 'list-040',
    title: '3 BHK for Rent on Park Street – Premium',
    description:
      'Heritage-style 3 BHK apartment on iconic Park Street. High ceilings, wooden flooring, and vintage charm blended with modern amenities. Walking distance to Flury\'s, Park Hotel, and Allen Park. Ideal for executives.',
    category: 'rent',
    propertyType: 'apartment',
    price: 30000,
    priceLabel: '₹30,000/month',
    deposit: 120000,
    bhk: 3,
    bathrooms: 3,
    balconies: 2,
    floor: '3rd of 6',
    totalFloors: 6,
    carpetArea: 1500,
    furnishing: 'furnished',
    ageOfProperty: '15 years',
    possessionStatus: 'ready',
    locality: 'Park Street',
    city: 'Kolkata',
    state: 'West Bengal',
    address: '17A, Park Street, Kolkata - 700016',
    lat: 22.5534,
    lng: 88.3547,
    images: [img(3), img(4), img(5)],
    amenities: ['parking', 'security', 'lift', 'power-backup', 'intercom'],
    verified: true,
    reraRegistered: false,
    directFromOwner: true,
    ownerId: 'owner-040',
    ownerName: 'Debashis Roy Chowdhury',
    ownerPhone: '+91 98250 22334',
    views: 2100,
    createdAt: '2024-10-15T10:00:00.000Z',
    updatedAt: '2024-12-20T15:00:00.000Z',
  },
  {
    id: 'list-041',
    title: '2 BHK for Rent in New Alipore – Family Friendly',
    description:
      'Spacious 2 BHK in the peaceful New Alipore area. Wide roads, tree-lined avenues, and close to schools and hospitals. Near Alipore Zoo and Rabindra Sarobar. Good for families with children.',
    category: 'rent',
    propertyType: 'apartment',
    price: 22000,
    priceLabel: '₹22,000/month',
    deposit: 88000,
    bhk: 2,
    bathrooms: 2,
    balconies: 1,
    floor: '4th of 7',
    totalFloors: 7,
    carpetArea: 950,
    furnishing: 'semifurnished',
    ageOfProperty: '5 years',
    possessionStatus: 'ready',
    locality: 'New Alipore',
    city: 'Kolkata',
    state: 'West Bengal',
    address: 'Biren Roy Road, New Alipore, Kolkata - 700053',
    lat: 22.5257,
    lng: 88.3368,
    images: [img(4), img(5), img(0)],
    amenities: ['parking', 'security', 'power-backup', 'garden', 'children-play'],
    verified: false,
    reraRegistered: false,
    directFromOwner: true,
    ownerId: 'owner-041',
    ownerName: 'Sneha Mukherjee',
    ownerPhone: '+91 98360 33445',
    views: 980,
    createdAt: '2024-12-08T08:00:00.000Z',
    updatedAt: '2024-12-22T09:00:00.000Z',
  },

  // ─── BUY AHMEDABAD (2) ─────────────────────────────────────────────
  {
    id: 'list-042',
    title: '3 BHK on SG Highway – Satellite Area',
    description:
      'Modern 3 BHK apartment on Sarkhej-Gandhinagar Highway. Close to Palladium Mall, ISCON Cross Road, and top schools. Spacious layout with large living room. Gated community with all modern amenities.',
    category: 'buy',
    propertyType: 'apartment',
    price: 6500000,
    priceLabel: '₹65 Lakhs',
    originalPrice: 7200000,
    bhk: 3,
    bathrooms: 3,
    balconies: 2,
    floor: '7th of 14',
    totalFloors: 14,
    carpetArea: 1450,
    furnishing: 'semifurnished',
    ageOfProperty: '2 years',
    possessionStatus: 'ready',
    locality: 'SG Highway',
    city: 'Ahmedabad',
    state: 'Gujarat',
    address: 'SG Highway, Near ISCON Cross Road, Ahmedabad - 380054',
    lat: 23.0699,
    lng: 72.5142,
    images: [img(5), img(0), img(1)],
    amenities: ['parking', 'gym', 'security', 'lift', 'power-backup', 'garden', 'children-play', 'cctv'],
    verified: true,
    reraRegistered: true,
    reraId: 'RERA/AG/2023/1234',
    directFromOwner: false,
    ownerId: 'owner-042',
    ownerName: 'Adani Realty',
    ownerPhone: '+91 98180 44556',
    views: 2560,
    createdAt: '2024-10-05T10:00:00.000Z',
    updatedAt: '2024-12-19T11:00:00.000Z',
  },
  {
    id: 'list-043',
    title: '2 BHK in Vastrapur – Near IIM',
    description:
      'Well-located 2 BHK in Vastrapur, near IIM Ahmedabad and Gujarat University. Walking distance to AlphaOne Mall and Vastrapur Lake. Clean, green, and well-planned neighbourhood. Perfect for families.',
    category: 'buy',
    propertyType: 'apartment',
    price: 4200000,
    priceLabel: '₹42 Lakhs',
    bhk: 2,
    bathrooms: 2,
    balconies: 1,
    floor: '4th of 8',
    totalFloors: 8,
    carpetArea: 980,
    furnishing: 'unfurnished',
    ageOfProperty: '4 years',
    possessionStatus: 'ready',
    locality: 'Vastrapur',
    city: 'Ahmedabad',
    state: 'Gujarat',
    address: 'Vastrapur, Near Drive-in Road, Ahmedabad - 380015',
    lat: 23.0304,
    lng: 72.5397,
    images: [img(0), img(1), img(2)],
    amenities: ['parking', 'security', 'lift', 'power-backup', 'water-supply', 'garden'],
    verified: true,
    reraRegistered: true,
    reraId: 'RERA/AG/2023/5678',
    directFromOwner: true,
    ownerId: 'owner-043',
    ownerName: 'Hemang Patel',
    ownerPhone: '+91 98290 55667',
    views: 1780,
    createdAt: '2024-11-08T09:00:00.000Z',
    updatedAt: '2024-12-21T08:00:00.000Z',
  },

  // ─── BUY JAIPUR (2) ────────────────────────────────────────────────
  {
    id: 'list-044',
    title: '3 BHK in Vaishali Nagar – Premium Society',
    description:
      'Elegant 3 BHK apartment in Vaishali Nagar, Jaipur\'s prime residential area. Close to Pink Square Mall, SMS Hospital, and world-class schools. Vitrified tiles, modular kitchen, and large balconies. Gated community.',
    category: 'buy',
    propertyType: 'apartment',
    price: 4500000,
    priceLabel: '₹45 Lakhs',
    bhk: 3,
    bathrooms: 3,
    balconies: 2,
    floor: '5th of 10',
    totalFloors: 10,
    carpetArea: 1350,
    furnishing: 'semifurnished',
    ageOfProperty: '3 years',
    possessionStatus: 'ready',
    locality: 'Vaishali Nagar',
    city: 'Jaipur',
    state: 'Rajasthan',
    address: 'Vaishali Nagar, Near Ajmer Road, Jaipur - 302021',
    lat: 26.8942,
    lng: 75.7891,
    images: [img(1), img(2), img(3)],
    amenities: ['parking', 'security', 'lift', 'power-backup', 'garden', 'children-play', 'cctv'],
    verified: true,
    reraRegistered: true,
    reraId: 'RAJ/P/2023/1234',
    directFromOwner: false,
    ownerId: 'owner-044',
    ownerName: 'Gehlot Builders',
    ownerPhone: '+91 98300 66778',
    views: 1890,
    createdAt: '2024-10-20T10:00:00.000Z',
    updatedAt: '2024-12-20T12:00:00.000Z',
  },
  {
    id: 'list-045',
    title: '2 BHK in Malviya Nagar – Near Transport Nagar',
    description:
      'Compact 2 BHK in Malviya Nagar, well-connected to Jaipur\'s major commercial hubs. Walking distance to Malviya Nagar Metro and Jawahar Nagar. Good rental potential. Well-ventilated with cross ventilation.',
    category: 'buy',
    propertyType: 'apartment',
    price: 2800000,
    priceLabel: '₹28 Lakhs',
    bhk: 2,
    bathrooms: 2,
    balconies: 1,
    floor: '3rd of 6',
    totalFloors: 6,
    carpetArea: 820,
    furnishing: 'unfurnished',
    ageOfProperty: '5 years',
    possessionStatus: 'ready',
    locality: 'Malviya Nagar',
    city: 'Jaipur',
    state: 'Rajasthan',
    address: 'Malviya Nagar, Jaipur - 302017',
    lat: 26.8840,
    lng: 75.8105,
    images: [img(2), img(3), img(4)],
    amenities: ['parking', 'security', 'lift', 'power-backup', 'water-supply'],
    verified: false,
    reraRegistered: true,
    reraId: 'RAJ/P/2023/5678',
    directFromOwner: true,
    ownerId: 'owner-045',
    ownerName: 'Vikram Singh Rathore',
    ownerPhone: '+91 98410 77889',
    views: 1120,
    createdAt: '2024-11-18T11:00:00.000Z',
    updatedAt: '2024-12-19T09:00:00.000Z',
  },

  // ─── RENT LUCKNOW (2) ──────────────────────────────────────────────
  {
    id: 'list-046',
    title: '3 BHK for Rent in Gomti Nagar – Vibhuti Khand',
    description:
      'Spacious 3 BHK in Gomti Nagar\'s Vibhuti Khand area. Close to Lucknow\'s IT City, Phoenix Palassio Mall, and Medanta Hospital. Well-maintained society with power backup and security. Ideal for families.',
    category: 'rent',
    propertyType: 'apartment',
    price: 18000,
    priceLabel: '₹18,000/month',
    deposit: 72000,
    bhk: 3,
    bathrooms: 3,
    balconies: 2,
    floor: '6th of 12',
    totalFloors: 12,
    carpetArea: 1400,
    furnishing: 'semifurnished',
    ageOfProperty: '3 years',
    possessionStatus: 'ready',
    locality: 'Gomti Nagar',
    city: 'Lucknow',
    state: 'Uttar Pradesh',
    address: 'Vibhuti Khand, Gomti Nagar, Lucknow - 226010',
    lat: 26.8528,
    lng: 81.0197,
    images: [img(3), img(4), img(5)],
    amenities: ['parking', 'security', 'lift', 'power-backup', 'garden', 'children-play'],
    verified: true,
    reraRegistered: false,
    directFromOwner: true,
    ownerId: 'owner-046',
    ownerName: 'Anil Mishra',
    ownerPhone: '+91 98170 88990',
    views: 1340,
    createdAt: '2024-11-28T09:00:00.000Z',
    updatedAt: '2024-12-22T07:00:00.000Z',
  },
  {
    id: 'list-047',
    title: '2 BHK for Rent in Hazratganj – Heart of Lucknow',
    description:
      'Classic 2 BHK in the heritage Hazratganj area. Walking distance to shopping arcades, cafes, and the iconic Hazratganj Chatori Gali. Well-ventilated flat with old-world charm. Ideal for working professionals.',
    category: 'rent',
    propertyType: 'apartment',
    price: 12000,
    priceLabel: '₹12,000/month',
    deposit: 48000,
    bhk: 2,
    bathrooms: 2,
    balconies: 1,
    floor: '2nd of 5',
    totalFloors: 5,
    carpetArea: 850,
    furnishing: 'semifurnished',
    ageOfProperty: '10 years',
    possessionStatus: 'ready',
    locality: 'Hazratganj',
    city: 'Lucknow',
    state: 'Uttar Pradesh',
    address: 'Hazratganj, Near Parivartan Chowk, Lucknow - 226001',
    lat: 26.8560,
    lng: 80.9486,
    images: [img(4), img(5), img(0)],
    amenities: ['parking', 'power-backup', 'water-supply'],
    verified: false,
    reraRegistered: false,
    directFromOwner: true,
    ownerId: 'owner-047',
    ownerName: 'Rizwan Ahmad',
    ownerPhone: '+91 98280 99001',
    views: 780,
    createdAt: '2024-12-10T10:00:00.000Z',
    updatedAt: '2024-12-21T11:00:00.000Z',
  },

  // ─── COMMERCIAL CHENNAI WAREHOUSE (1) ──────────────────────────────
  {
    id: 'list-048',
    title: 'Industrial Warehouse in Chennai – 5000 sqft',
    description:
      'Large industrial warehouse available for sale in the Maraimalai Nagar industrial belt. Near GST Road and Oragadam SIPCOT. Built with heavy-duty flooring, 40ft container access, fire safety systems. 3-phase power with 200 KVA transformer.',
    category: 'commercial',
    propertyType: 'commercial-warehouse',
    price: 4500000,
    priceLabel: '₹45 Lakhs',
    bhk: 0,
    bathrooms: 2,
    balconies: 0,
    floor: 'Ground',
    totalFloors: 1,
    carpetArea: 5000,
    furnishing: 'unfurnished',
    ageOfProperty: '5 years',
    possessionStatus: 'ready',
    locality: 'Guindy',
    city: 'Chennai',
    state: 'Tamil Nadu',
    address: 'Maraimalai Nagar Industrial Area, GST Road, Chennai - 603209',
    lat: 12.7912,
    lng: 80.0108,
    images: [img(5), img(0), img(1)],
    amenities: ['power-backup', 'parking', 'fire-safety', 'cctv', 'water-supply'],
    verified: true,
    reraRegistered: false,
    directFromOwner: true,
    ownerId: 'owner-048',
    ownerName: 'Karthik Industries',
    ownerPhone: '+91 98390 00112',
    views: 890,
    createdAt: '2024-10-28T10:00:00.000Z',
    updatedAt: '2024-12-18T09:00:00.000Z',
  },

  // ─── BONUS PROPERTIES (2) ─────────────────────────────────────────
  {
    id: 'list-049',
    title: '4 BHK in Whitefield – Villa Project Bangalore',
    description:
      'Premium 4 BHK villa in a gated community in Whitefield. Private garden, rooftop terrace, and modular kitchen. Near ITPL and Forum Shantiniketan. International school within the campus. Ideal for luxury living.',
    category: 'buy',
    propertyType: 'villa',
    price: 18000000,
    priceLabel: '₹1.8 Cr',
    bhk: 4,
    bathrooms: 4,
    balconies: 2,
    floor: 'Ground + 1',
    totalFloors: 2,
    carpetArea: 2400,
    superBuiltUpArea: 2800,
    plotArea: 1800,
    furnishing: 'semifurnished',
    ageOfProperty: '2 years',
    possessionStatus: 'ready',
    locality: 'Whitefield',
    city: 'Bangalore',
    state: 'Karnataka',
    address: 'Prestige Lakeside Habitat, Whitefield, Bangalore - 560066',
    lat: 12.9710,
    lng: 77.7410,
    images: [img(0), img(1), img(2)],
    amenities: ['parking', 'gym', 'pool', 'security', 'garden', 'power-backup', 'clubhouse', 'cctv', 'vaastu', 'children-play', 'jogging-track'],
    verified: true,
    reraRegistered: true,
    reraId: 'RERA/PRM/KA/RERA/7890/2024',
    directFromOwner: false,
    ownerId: 'owner-049',
    ownerName: 'Prestige Estates',
    ownerPhone: '+91 98500 11234',
    views: 3210,
    createdAt: '2024-08-12T09:00:00.000Z',
    updatedAt: '2024-12-20T13:00:00.000Z',
  },
  {
    id: 'list-050',
    title: '2 BHK in Gachibowli – Budget Apartment Hyderabad',
    description:
      'Affordable 2 BHK in Gachibowli near IT corridor. Compact layout with efficient space utilization. Walking distance to bus stop and restaurants. Ideal for bachelors and young IT professionals starting their career.',
    category: 'buy',
    propertyType: 'apartment',
    price: 5500000,
    priceLabel: '₹55 Lakhs',
    bhk: 2,
    bathrooms: 2,
    balconies: 1,
    floor: '4th of 10',
    totalFloors: 10,
    carpetArea: 900,
    furnishing: 'unfurnished',
    ageOfProperty: '4 years',
    possessionStatus: 'ready',
    locality: 'Gachibowli',
    city: 'Hyderabad',
    state: 'Telangana',
    address: 'Gachibowli, Near University of Hyderabad, Hyderabad - 500032',
    lat: 17.4340,
    lng: 78.3600,
    images: [img(1), img(2), img(3)],
    amenities: ['parking', 'security', 'lift', 'power-backup', 'water-supply'],
    verified: false,
    reraRegistered: true,
    reraId: 'TS/RERA/P027/2023',
    directFromOwner: true,
    ownerId: 'owner-050',
    ownerName: 'Srinivas Rao',
    ownerPhone: '+91 98610 22345',
    views: 1560,
    createdAt: '2024-11-05T10:00:00.000Z',
    updatedAt: '2024-12-19T15:00:00.000Z',
  },
];

// ═══════════════════════════════════════════════════════════════════════
// SECTION B: CITY DATA (all 10 cities)
// ═══════════════════════════════════════════════════════════════════════

export const CITY_DATA = [
  { name: 'Chennai', image: img(2), propertyCount: 12500, avgPrice: '₹6,500/sqft', growth: '+8.2%', topLocalities: ['Anna Nagar', 'OMR', 'Velachery', 'Adyar', 'T Nagar'] },
  { name: 'Mumbai', image: img(3), propertyCount: 18500, avgPrice: '₹18,000/sqft', growth: '+5.6%', topLocalities: ['Bandra', 'Andheri', 'Powai', 'Worli', 'Juhu'] },
  { name: 'Delhi', image: img(4), propertyCount: 15800, avgPrice: '₹10,200/sqft', growth: '+12.8%', topLocalities: ['Dwarka', 'Rohini', 'Vasant Kunj', 'Saket', 'Rajouri Garden'] },
  { name: 'Bangalore', image: img(5), propertyCount: 14200, avgPrice: '₹9,800/sqft', growth: '+22.1%', topLocalities: ['Whitefield', 'Koramangala', 'HSR Layout', 'Electronic City', 'Indiranagar'] },
  { name: 'Hyderabad', image: img(0), propertyCount: 11800, avgPrice: '₹7,200/sqft', growth: '+25.3%', topLocalities: ['Gachibowli', 'Madhapur', 'Jubilee Hills', 'Kondapur', 'Miyapur'] },
  { name: 'Kolkata', image: img(1), propertyCount: 9800, avgPrice: '₹5,500/sqft', growth: '+6.4%', topLocalities: ['Salt Lake', 'Park Street', 'New Alipore', 'Ballygunge', 'Rajaratna'] },
  { name: 'Pune', image: img(2), propertyCount: 10500, avgPrice: '₹7,000/sqft', growth: '+18.5%', topLocalities: ['Hinjewadi', 'Wakad', 'Baner', 'Kharadi', 'Viman Nagar'] },
  { name: 'Ahmedabad', image: img(3), propertyCount: 8200, avgPrice: '₹4,800/sqft', growth: '+9.1%', topLocalities: ['SG Highway', 'Vastrapur', 'Bodakdev', 'Thaltej', 'Navrangpura'] },
  { name: 'Jaipur', image: img(4), propertyCount: 6500, avgPrice: '₹3,800/sqft', growth: '+7.3%', topLocalities: ['Vaishali Nagar', 'Malviya Nagar', 'Mansarovar', 'Tonk Road', 'C-Scheme'] },
  { name: 'Lucknow', image: img(5), propertyCount: 5800, avgPrice: '₹4,200/sqft', growth: '+10.5%', topLocalities: ['Gomti Nagar', 'Hazratganj', 'Kapoorthala', 'Aliganj', 'Aashiana'] },
];

// ═══════════════════════════════════════════════════════════════════════
// SECTION C: BLOG ARTICLES (9 articles)
// ═══════════════════════════════════════════════════════════════════════

export const BLOG_ARTICLES = [
  { id: 'blog-1', title: '5 Tips for First-Time Home Buyers in 2024', excerpt: 'Buying your first home is a big decision. Here are 5 essential tips to help you navigate the process, from checking your credit score to understanding hidden costs.', category: 'Buying Guide', image: '/blog/article-1.jpg', author: 'Arjun Mehta', date: 'Dec 20, 2024', readTime: '5 min read' },
  { id: 'blog-2', title: 'Understanding RERA: What Home Buyers Need to Know', excerpt: 'RERA protects home buyers from fraud and delays. Learn about your rights as a buyer, how to verify RERA registration, and what to do if a project is delayed.', category: 'Legal', image: '/blog/article-2.jpg', author: 'Priya Sharma', date: 'Dec 15, 2024', readTime: '7 min read' },
  { id: 'blog-3', title: 'Top 10 Investment Hotspots in India for 2025', excerpt: 'From Hyderabad to Bangalore, discover the top cities and localities where property prices are expected to rise the most. Data-driven insights for smart investors.', category: 'Investment', image: '/blog/article-3.jpg', author: 'Vikram Patel', date: 'Dec 10, 2024', readTime: '8 min read' },
  { id: 'blog-4', title: 'Renting vs Buying: The Complete 2024 Guide', excerpt: 'Should you rent or buy? This comprehensive guide breaks down the financial, emotional, and lifestyle factors to help you make the right choice for your situation.', category: 'Buying Guide', image: '/blog/article-4.jpg', author: 'Sneha Reddy', date: 'Dec 5, 2024', readTime: '10 min read' },
  { id: 'blog-5', title: 'How to Check Property Legal Documents', excerpt: 'Before buying any property, verify these critical legal documents: title deed, encumbrance certificate, building plan approval, and tax receipts. A step-by-step checklist.', category: 'Legal', image: '/blog/article-5.jpg', author: 'Rajesh Kumar', date: 'Nov 28, 2024', readTime: '6 min read' },
  { id: 'blog-6', title: 'Home Loan Interest Rates Compared — Dec 2024', excerpt: 'We compare home loan rates from SBI, HDFC, ICICI, Axis, and LIC Housing. Find the lowest rates, best processing fees, and tips to get your loan approved faster.', category: 'Finance', image: '/blog/article-6.jpg', author: 'Amit Agarwal', date: 'Nov 20, 2024', readTime: '6 min read' },
  { id: 'blog-7', title: 'Vastu Tips for Your New Home', excerpt: 'Planning a new home? Follow these practical Vastu Shastra tips for each room — from the main entrance direction to kitchen placement and bedroom positioning.', category: 'Interior', image: '/blog/article-7.jpg', author: 'Nisha Verma', date: 'Nov 15, 2024', readTime: '5 min read' },
  { id: 'blog-8', title: 'Best Localities for Families in Metro Cities', excerpt: 'Looking for the perfect family neighbourhood? We rank the top localities across Mumbai, Delhi, Bangalore, and Hyderabad based on schools, safety, parks, and connectivity.', category: 'Lifestyle', image: '/blog/article-8.jpg', author: 'Deepa Nair', date: 'Nov 8, 2024', readTime: '8 min read' },
  { id: 'blog-9', title: 'Complete Guide to Property Registration in India', excerpt: 'A detailed walkthrough of the property registration process including stamp duty rates, required documents, sub-registrar office procedures, and common pitfalls to avoid.', category: 'Legal', image: '/blog/article-9.jpg', author: 'Ravi Iyer', date: 'Nov 1, 2024', readTime: '9 min read' },
];

// ═══════════════════════════════════════════════════════════════════════
// SECTION D: SUBSCRIPTION PLANS (4 tiers)
// ═══════════════════════════════════════════════════════════════════════

export const SUBSCRIPTION_PLANS = [
  {
    id: 'free',
    name: 'Free',
    price: 0,
    duration: 'forever',
    features: [
      'Browse up to 10 properties per day',
      'Basic search filters',
      'View property details',
      'Contact owners via platform',
      'Access to market trends',
    ],
    badge: '',
  },
  {
    id: 'basic',
    name: 'Basic',
    price: 499,
    duration: 'per month',
    features: [
      'Unlimited property browsing',
      'Advanced search & filters',
      'Save up to 20 shortlisted properties',
      'Price drop alerts',
      'Locality insights & ratings',
      'EMI calculator access',
      'Email support',
    ],
    badge: '',
  },
  {
    id: 'plus',
    name: 'Plus',
    price: 999,
    duration: 'per month',
    popular: true,
    features: [
      'Everything in Basic',
      'Compare up to 5 properties side-by-side',
      'Priority owner contact details',
      'Verified property badges',
      'Detailed price trend analysis',
      'Legal document checklist',
      'Chat with verified agents',
      'WhatsApp notifications',
      'Priority phone support',
    ],
    badge: 'MOST POPULAR',
  },
  {
    id: 'premium',
    name: 'Premium',
    price: 1999,
    duration: 'per month',
    features: [
      'Everything in Plus',
      'Dedicated relationship manager',
      'Free legal consultation (1 session/month)',
      'Home loan assistance & comparison',
      'Exclusive pre-launch deals',
      'Property valuation report',
      'Interior design consultation',
      'Post-property listing for free',
      'Airport pickup for site visits',
      '24/7 concierge support',
    ],
    badge: 'BEST VALUE',
  },
];

// ═══════════════════════════════════════════════════════════════════════
// SECTION E: EXPANDED PRICE TRENDS (30 localities across 10 cities)
// ═══════════════════════════════════════════════════════════════════════

// ─── Mumbai Localities ──────────────────────────────────────────────
export const mockPriceTrendsExtended: Record<string, PriceTrend[]> = {
  ...mockPriceTrends,
  Bandra: [
    { month: 'Jan', price: 28000 }, { month: 'Feb', price: 28500 }, { month: 'Mar', price: 28200 },
    { month: 'Apr', price: 28800 }, { month: 'May', price: 29200 }, { month: 'Jun', price: 29500 },
    { month: 'Jul', price: 29800 }, { month: 'Aug', price: 30200 }, { month: 'Sep', price: 30500 },
    { month: 'Oct', price: 31000 }, { month: 'Nov', price: 31500 }, { month: 'Dec', price: 32000 },
  ],
  Andheri: [
    { month: 'Jan', price: 18000 }, { month: 'Feb', price: 18200 }, { month: 'Mar', price: 18400 },
    { month: 'Apr', price: 18500 }, { month: 'May', price: 18800 }, { month: 'Jun', price: 19000 },
    { month: 'Jul', price: 19200 }, { month: 'Aug', price: 19500 }, { month: 'Sep', price: 19700 },
    { month: 'Oct', price: 20000 }, { month: 'Nov', price: 20300 }, { month: 'Dec', price: 20500 },
  ],
  Powai: [
    { month: 'Jan', price: 15000 }, { month: 'Feb', price: 15200 }, { month: 'Mar', price: 15500 },
    { month: 'Apr', price: 15800 }, { month: 'May', price: 16000 }, { month: 'Jun', price: 16200 },
    { month: 'Jul', price: 16400 }, { month: 'Aug', price: 16700 }, { month: 'Sep', price: 16900 },
    { month: 'Oct', price: 17100 }, { month: 'Nov', price: 17300 }, { month: 'Dec', price: 17500 },
  ],
  // ─── Delhi Localities ─────────────────────────────────────────────
  Dwarka: [
    { month: 'Jan', price: 7500 }, { month: 'Feb', price: 7580 }, { month: 'Mar', price: 7650 },
    { month: 'Apr', price: 7700 }, { month: 'May', price: 7780 }, { month: 'Jun', price: 7850 },
    { month: 'Jul', price: 7900 }, { month: 'Aug', price: 8000 }, { month: 'Sep', price: 8100 },
    { month: 'Oct', price: 8200 }, { month: 'Nov', price: 8350 }, { month: 'Dec', price: 8500 },
  ],
  Rohini: [
    { month: 'Jan', price: 6500 }, { month: 'Feb', price: 6540 }, { month: 'Mar', price: 6580 },
    { month: 'Apr', price: 6620 }, { month: 'May', price: 6680 }, { month: 'Jun', price: 6720 },
    { month: 'Jul', price: 6780 }, { month: 'Aug', price: 6850 }, { month: 'Sep', price: 6900 },
    { month: 'Oct', price: 6950 }, { month: 'Nov', price: 7000 }, { month: 'Dec', price: 7100 },
  ],
  'Vasant Kunj': [
    { month: 'Jan', price: 12000 }, { month: 'Feb', price: 12100 }, { month: 'Mar', price: 12300 },
    { month: 'Apr', price: 12500 }, { month: 'May', price: 12700 }, { month: 'Jun', price: 13000 },
    { month: 'Jul', price: 13200 }, { month: 'Aug', price: 13400 }, { month: 'Sep', price: 13600 },
    { month: 'Oct', price: 13700 }, { month: 'Nov', price: 13800 }, { month: 'Dec', price: 14000 },
  ],
  // ─── Bangalore Localities ─────────────────────────────────────────
  Whitefield: [
    { month: 'Jan', price: 6000 }, { month: 'Feb', price: 6080 }, { month: 'Mar', price: 6150 },
    { month: 'Apr', price: 6250 }, { month: 'May', price: 6350 }, { month: 'Jun', price: 6450 },
    { month: 'Jul', price: 6550 }, { month: 'Aug', price: 6650 }, { month: 'Sep', price: 6750 },
    { month: 'Oct', price: 6850 }, { month: 'Nov', price: 7000 }, { month: 'Dec', price: 7200 },
  ],
  Koramangala: [
    { month: 'Jan', price: 8500 }, { month: 'Feb', price: 8600 }, { month: 'Mar', price: 8750 },
    { month: 'Apr', price: 8850 }, { month: 'May', price: 9000 }, { month: 'Jun', price: 9150 },
    { month: 'Jul', price: 9300 }, { month: 'Aug', price: 9400 }, { month: 'Sep', price: 9550 },
    { month: 'Oct', price: 9700 }, { month: 'Nov', price: 9850 }, { month: 'Dec', price: 10000 },
  ],
  'HSR Layout': [
    { month: 'Jan', price: 9000 }, { month: 'Feb', price: 9100 }, { month: 'Mar', price: 9250 },
    { month: 'Apr', price: 9400 }, { month: 'May', price: 9550 }, { month: 'Jun', price: 9700 },
    { month: 'Jul', price: 9850 }, { month: 'Aug', price: 10000 }, { month: 'Sep', price: 10200 },
    { month: 'Oct', price: 10400 }, { month: 'Nov', price: 10600 }, { month: 'Dec', price: 10800 },
  ],
  // ─── Hyderabad Localities ─────────────────────────────────────────
  Gachibowli: [
    { month: 'Jan', price: 7000 }, { month: 'Feb', price: 7100 }, { month: 'Mar', price: 7250 },
    { month: 'Apr', price: 7400 }, { month: 'May', price: 7550 }, { month: 'Jun', price: 7700 },
    { month: 'Jul', price: 7850 }, { month: 'Aug', price: 8000 }, { month: 'Sep', price: 8200 },
    { month: 'Oct', price: 8400 }, { month: 'Nov', price: 8600 }, { month: 'Dec', price: 8800 },
  ],
  Madhapur: [
    { month: 'Jan', price: 6500 }, { month: 'Feb', price: 6580 }, { month: 'Mar', price: 6650 },
    { month: 'Apr', price: 6720 }, { month: 'May', price: 6800 }, { month: 'Jun', price: 6900 },
    { month: 'Jul', price: 6980 }, { month: 'Aug', price: 7050 }, { month: 'Sep', price: 7150 },
    { month: 'Oct', price: 7250 }, { month: 'Nov', price: 7350 }, { month: 'Dec', price: 7500 },
  ],
  'Jubilee Hills': [
    { month: 'Jan', price: 12000 }, { month: 'Feb', price: 12200 }, { month: 'Mar', price: 12400 },
    { month: 'Apr', price: 12600 }, { month: 'May', price: 12900 }, { month: 'Jun', price: 13100 },
    { month: 'Jul', price: 13400 }, { month: 'Aug', price: 13600 }, { month: 'Sep', price: 13800 },
    { month: 'Oct', price: 14000 }, { month: 'Nov', price: 14200 }, { month: 'Dec', price: 14500 },
  ],
  // ─── Pune Localities ──────────────────────────────────────────────
  Hinjewadi: [
    { month: 'Jan', price: 5500 }, { month: 'Feb', price: 5550 }, { month: 'Mar', price: 5600 },
    { month: 'Apr', price: 5680 }, { month: 'May', price: 5750 }, { month: 'Jun', price: 5800 },
    { month: 'Jul', price: 5880 }, { month: 'Aug', price: 5950 }, { month: 'Sep', price: 6000 },
    { month: 'Oct', price: 6100 }, { month: 'Nov', price: 6200 }, { month: 'Dec', price: 6300 },
  ],
  Wakad: [
    { month: 'Jan', price: 6000 }, { month: 'Feb', price: 6050 }, { month: 'Mar', price: 6120 },
    { month: 'Apr', price: 6180 }, { month: 'May', price: 6250 }, { month: 'Jun', price: 6300 },
    { month: 'Jul', price: 6380 }, { month: 'Aug', price: 6450 }, { month: 'Sep', price: 6500 },
    { month: 'Oct', price: 6580 }, { month: 'Nov', price: 6650 }, { month: 'Dec', price: 6750 },
  ],
  Baner: [
    { month: 'Jan', price: 7500 }, { month: 'Feb', price: 7580 }, { month: 'Mar', price: 7680 },
    { month: 'Apr', price: 7750 }, { month: 'May', price: 7850 }, { month: 'Jun', price: 7950 },
    { month: 'Jul', price: 8050 }, { month: 'Aug', price: 8150 }, { month: 'Sep', price: 8250 },
    { month: 'Oct', price: 8400 }, { month: 'Nov', price: 8550 }, { month: 'Dec', price: 8700 },
  ],
  // ─── Kolkata Localities ───────────────────────────────────────────
  'Salt Lake': [
    { month: 'Jan', price: 4500 }, { month: 'Feb', price: 4550 }, { month: 'Mar', price: 4600 },
    { month: 'Apr', price: 4650 }, { month: 'May', price: 4680 }, { month: 'Jun', price: 4720 },
    { month: 'Jul', price: 4780 }, { month: 'Aug', price: 4820 }, { month: 'Sep', price: 4880 },
    { month: 'Oct', price: 4920 }, { month: 'Nov', price: 4980 }, { month: 'Dec', price: 5050 },
  ],
  'Park Street': [
    { month: 'Jan', price: 8000 }, { month: 'Feb', price: 8080 }, { month: 'Mar', price: 8150 },
    { month: 'Apr', price: 8250 }, { month: 'May', price: 8350 }, { month: 'Jun', price: 8450 },
    { month: 'Jul', price: 8550 }, { month: 'Aug', price: 8650 }, { month: 'Sep', price: 8750 },
    { month: 'Oct', price: 8850 }, { month: 'Nov', price: 9000 }, { month: 'Dec', price: 9200 },
  ],
  'New Alipore': [
    { month: 'Jan', price: 6000 }, { month: 'Feb', price: 6080 }, { month: 'Mar', price: 6120 },
    { month: 'Apr', price: 6180 }, { month: 'May', price: 6250 }, { month: 'Jun', price: 6300 },
    { month: 'Jul', price: 6380 }, { month: 'Aug', price: 6450 }, { month: 'Sep', price: 6500 },
    { month: 'Oct', price: 6580 }, { month: 'Nov', price: 6650 }, { month: 'Dec', price: 6750 },
  ],
  // ─── Ahmedabad Localities ─────────────────────────────────────────
  'SG Highway': [
    { month: 'Jan', price: 4500 }, { month: 'Feb', price: 4580 }, { month: 'Mar', price: 4650 },
    { month: 'Apr', price: 4720 }, { month: 'May', price: 4800 }, { month: 'Jun', price: 4880 },
    { month: 'Jul', price: 4950 }, { month: 'Aug', price: 5020 }, { month: 'Sep', price: 5100 },
    { month: 'Oct', price: 5180 }, { month: 'Nov', price: 5250 }, { month: 'Dec', price: 5350 },
  ],
  Vastrapur: [
    { month: 'Jan', price: 4000 }, { month: 'Feb', price: 4050 }, { month: 'Mar', price: 4100 },
    { month: 'Apr', price: 4150 }, { month: 'May', price: 4200 }, { month: 'Jun', price: 4250 },
    { month: 'Jul', price: 4320 }, { month: 'Aug', price: 4380 }, { month: 'Sep', price: 4450 },
    { month: 'Oct', price: 4500 }, { month: 'Nov', price: 4580 }, { month: 'Dec', price: 4650 },
  ],
  // ─── Jaipur Localities ────────────────────────────────────────────
  'Vaishali Nagar': [
    { month: 'Jan', price: 3500 }, { month: 'Feb', price: 3550 }, { month: 'Mar', price: 3600 },
    { month: 'Apr', price: 3650 }, { month: 'May', price: 3700 }, { month: 'Jun', price: 3750 },
    { month: 'Jul', price: 3800 }, { month: 'Aug', price: 3850 }, { month: 'Sep', price: 3900 },
    { month: 'Oct', price: 3980 }, { month: 'Nov', price: 4050 }, { month: 'Dec', price: 4120 },
  ],
  'Malviya Nagar': [
    { month: 'Jan', price: 3800 }, { month: 'Feb', price: 3850 }, { month: 'Mar', price: 3900 },
    { month: 'Apr', price: 3950 }, { month: 'May', price: 4000 }, { month: 'Jun', price: 4060 },
    { month: 'Jul', price: 4120 }, { month: 'Aug', price: 4180 }, { month: 'Sep', price: 4250 },
    { month: 'Oct', price: 4300 }, { month: 'Nov', price: 4350 }, { month: 'Dec', price: 4420 },
  ],
  // ─── Lucknow Localities ───────────────────────────────────────────
  'Gomti Nagar': [
    { month: 'Jan', price: 4000 }, { month: 'Feb', price: 4050 }, { month: 'Mar', price: 4100 },
    { month: 'Apr', price: 4180 }, { month: 'May', price: 4250 }, { month: 'Jun', price: 4300 },
    { month: 'Jul', price: 4380 }, { month: 'Aug', price: 4450 }, { month: 'Sep', price: 4520 },
    { month: 'Oct', price: 4600 }, { month: 'Nov', price: 4680 }, { month: 'Dec', price: 4750 },
  ],
  Hazratganj: [
    { month: 'Jan', price: 5500 }, { month: 'Feb', price: 5580 }, { month: 'Mar', price: 5650 },
    { month: 'Apr', price: 5720 }, { month: 'May', price: 5800 }, { month: 'Jun', price: 5880 },
    { month: 'Jul', price: 5950 }, { month: 'Aug', price: 6020 }, { month: 'Sep', price: 6100 },
    { month: 'Oct', price: 6180 }, { month: 'Nov', price: 6250 }, { month: 'Dec', price: 6350 },
  ],
};

// ═══════════════════════════════════════════════════════════════════════
// SECTION F: EXPANDED LOCALITY INSIGHTS (30 localities across 10 cities)
// ═══════════════════════════════════════════════════════════════════════

export const mockLocalityInsightsExtended: Record<string, LocalityInsight> = {
  ...mockLocalityInsights,
  // ─── Mumbai ─────────────────────────────────────────────────────────
  Bandra: { safety: 4.0, connectivity: 4.5, infrastructure: 4.5, airQuality: 3.0, nightlife: 4.5, restaurants: 5.0 },
  Andheri: { safety: 3.5, connectivity: 4.5, infrastructure: 4.0, airQuality: 2.5, nightlife: 3.5, restaurants: 4.0 },
  Powai: { safety: 4.5, connectivity: 3.5, infrastructure: 4.0, airQuality: 3.5, nightlife: 3.0, restaurants: 3.5 },
  // ─── Delhi ──────────────────────────────────────────────────────────
  Dwarka: { safety: 4.0, connectivity: 4.0, infrastructure: 4.5, airQuality: 2.5, nightlife: 3.0, restaurants: 3.5 },
  Rohini: { safety: 4.0, connectivity: 3.5, infrastructure: 3.5, airQuality: 2.5, nightlife: 3.0, restaurants: 3.5 },
  'Vasant Kunj': { safety: 4.5, connectivity: 4.0, infrastructure: 4.5, airQuality: 3.0, nightlife: 3.5, restaurants: 4.0 },
  // ─── Bangalore ──────────────────────────────────────────────────────
  Whitefield: { safety: 4.0, connectivity: 3.5, infrastructure: 4.0, airQuality: 4.0, nightlife: 3.0, restaurants: 3.5 },
  Koramangala: { safety: 4.0, connectivity: 4.5, infrastructure: 4.0, airQuality: 3.5, nightlife: 4.5, restaurants: 5.0 },
  'HSR Layout': { safety: 4.5, connectivity: 4.0, infrastructure: 4.5, airQuality: 3.5, nightlife: 4.0, restaurants: 4.5 },
  // ─── Hyderabad ──────────────────────────────────────────────────────
  Gachibowli: { safety: 4.5, connectivity: 4.0, infrastructure: 4.5, airQuality: 4.0, nightlife: 3.5, restaurants: 4.0 },
  Madhapur: { safety: 4.0, connectivity: 4.5, infrastructure: 4.0, airQuality: 3.5, nightlife: 4.0, restaurants: 4.5 },
  'Jubilee Hills': { safety: 4.5, connectivity: 4.0, infrastructure: 4.5, airQuality: 3.5, nightlife: 4.5, restaurants: 4.5 },
  // ─── Pune ───────────────────────────────────────────────────────────
  Hinjewadi: { safety: 4.0, connectivity: 3.5, infrastructure: 3.5, airQuality: 4.0, nightlife: 2.5, restaurants: 3.0 },
  Wakad: { safety: 3.5, connectivity: 4.0, infrastructure: 3.5, airQuality: 3.5, nightlife: 3.0, restaurants: 3.5 },
  Baner: { safety: 4.0, connectivity: 4.0, infrastructure: 4.0, airQuality: 3.5, nightlife: 4.0, restaurants: 4.5 },
  // ─── Kolkata ────────────────────────────────────────────────────────
  'Salt Lake': { safety: 4.0, connectivity: 4.0, infrastructure: 4.0, airQuality: 2.5, nightlife: 3.0, restaurants: 3.5 },
  'Park Street': { safety: 3.5, connectivity: 4.5, infrastructure: 4.0, airQuality: 2.5, nightlife: 4.5, restaurants: 5.0 },
  'New Alipore': { safety: 4.5, connectivity: 4.0, infrastructure: 4.0, airQuality: 3.0, nightlife: 3.5, restaurants: 4.0 },
  // ─── Ahmedabad ──────────────────────────────────────────────────────
  'SG Highway': { safety: 4.0, connectivity: 4.5, infrastructure: 4.5, airQuality: 3.0, nightlife: 3.0, restaurants: 3.5 },
  Vastrapur: { safety: 4.5, connectivity: 4.0, infrastructure: 4.0, airQuality: 3.0, nightlife: 3.5, restaurants: 4.0 },
  // ─── Jaipur ────────────────────────────────────────────────────────
  'Vaishali Nagar': { safety: 4.0, connectivity: 4.0, infrastructure: 3.5, airQuality: 3.0, nightlife: 3.0, restaurants: 3.5 },
  'Malviya Nagar': { safety: 4.0, connectivity: 3.5, infrastructure: 3.5, airQuality: 3.0, nightlife: 3.5, restaurants: 4.0 },
  // ─── Lucknow ────────────────────────────────────────────────────────
  'Gomti Nagar': { safety: 4.5, connectivity: 4.0, infrastructure: 4.0, airQuality: 3.0, nightlife: 3.0, restaurants: 3.5 },
  Hazratganj: { safety: 3.5, connectivity: 4.5, infrastructure: 4.0, airQuality: 2.5, nightlife: 4.0, restaurants: 4.5 },
};
